=== Implementation and operation of a Global Service

==== Procedure for registration of a new Global Service

Successful operations of WIS will depend on having a set of Global Services running state of the art IT environments, with a very high level of reliability so that all WIS Users and WIS2 Nodes will be able to access and provide data they need for their duties.

Depending on the nature of the Global Service, the following is considered to be the minimum of centres operating a Global Service, so that collectively, the level of service is 100% (or very close):
* Three (3) Global Brokers - Each Global Broker connected to at least two (2) other Global Broker
* Three (3) Global Caches - Each Global Cache connected to at least two (2) Global Broker and should be able to download the data from all WIS Nodes providing Core data
* Two (2) Global Discovery Catalogues - Each Global Discovery Catalogue connected to at least one (1) Global Broker
* Two (2) Global Monitoring Centres - Each Global Monitoring Centre should fetch the metrics from all WIS Nodes and all other Global Service

In addition to the above, WIS architecture can accomodate adding (or removing) Global Services. Candidate WIS Centres should inform their WIS Focal Point and contact the WMO Secretariat to discuss their offer to provide a Global Service.

Running a Global Service is a significant commitment for a WIS Centre.  To maintain a very high level of service of WIS, each Global Service will have a key role to play.

WMO Secretariat, based on the current situation of WIS (How many Global Brokers ? A need for additional Cache ?), will propose to the WIS Centre the preferred solution to improve the overall level of service of WIS.

A WIS Centre may decide to run the proposed service or may decide to run another one.

The Manual on WIS, the Guide and other material available will help WIS Centres in deciding the best way forward.

When decided, the WIS Focal Point will inform WMO Secretariat of its preference. Depending on the type of Global Service, WMO Secretariat will provide a checklist to the WIS Centre so that the future Global Service can be included in WIS Operations.

WMO Secretariat will include the new Global Service in the next fast track cycle of WIS Operation. When endorsed by the President of the Infrastructure Commission, the WIS Centre will be included in the list of Global Service operators. 

A WIS Centre must commit to running the Global Service for a minimum of four (4) years.

WMO Secretariat and other Global Services will make the required changes to include the new Global Service in WIS Operations.

==== Performance management and monitoring of a Global Service

===== Service levels, performance indicators, and fair-usage policies
* Each WIS Centre operating a WIS2 Node will be responsible in achieving the highest possible level of service based on their resources and capabilities.
* All Global Services, and in particular Global Brokers and Global Caches, are collectively responsible in making the WIS a reliable and efficient mean to exchange data required for the operations of all WIS Centres. The agreed architecture provides a redundant solution where the failure of one component will not impact the overall level of service of WIS. 
* Each Global Service should aim at achieving at least 99.5% availibility of the service they propose. This is not a contractual target. It should be considered by the entity providing the Global Service as a guideline when designing and operating the Global Service.
* A Global Broker:
** should support a minimum of 200 WIS Nodes or Global Services
** should support a minimum of 1000 subscribers. 
** should support processing of a minimum of 10000 messages per second
* A Global Cache:
** should support a mimimum of 100 GB of data in the cache
** should support a minimum of 1000 simultaneous downloads
** could limit the number of simultaneous connections from a user (known by its originating source IP) to 5
** could limit the bandwidth usage of the service to 1Gb/s
* A Global Monitor: 
** should support a minimum of 50 metrics providers
** should support 200 simultaneous access to the dashboard
** could limit the bandwidth usage of the service to 100Mb/s
* A Global Discovery Catalogue:
** should support a minimum of 20000 metadata records
** should support a minimum of 50 requests per second to the API endpoint

===== Provision of metrics

In the following sections and for each Global Service, a set of metrics is defined. Each Global Service will provide those metrics. They will then be ingested by Global Monitoring Services.

==== Global Broker

===== Technical considerations

* As detailed above, there will be at least three (3) instances of Global Broker to ensure highly available, low latency global provision of messages within WIS.
* A Global Broker instance subscribes to messages from WIS Centres, Global Caches and other Global Brokers. The Global Broker should aim at subscribing to all WIS Centres. If this is not possible, for whatever reason, the Global Broker should inform WMO Secretariat so that situation is documented.
* Every WIS Centre or Global Service must have subscriptions from at least two Global Brokers.
* For full global coverage, a Global Broker instance will subscribe to messages from at least two (2) other Global Brokers.

* A Global Broker is built around two software components:
** An off the shelf broker implementing both MQTT 3.1.1 and MQTT 5.0 in a highly-available setup, typically in a cluster mode. Tools such as EMQX, HiveMQ, VerneMQ are compliant with these requirements. It must be noted that the open source version of Mosquitto cannot be clustered and therefore should not be used as part of a Global Broker.
** Additional features including anti-loop detection, notification message format compliance, validation of the published topic, and provision of metrics are required. 

* When receiviong a message from a WIS Centre or Global Service broker, The metrics ``wmo_wis2_gb_messages_received_total`` will be increased by 1.
* A Global Broker will check if the topic received is valid (a metadata record must exist for a data under this topic), discarding non-compliant messages and raising an alert. The metrics ``wmo_wis2_gb_messages_no_metadata_total`` will be increased by 1.
* A Global Broker will validate notification messages against the standard format (see Notification message format and structure), discarding non-compliant messages and raising an alert. The metrics ``wmo_wis2_gb_messages_invalid_total`` will be increased by 1.
* A Global Broker instance will republish a message only once. Using the message id as defined in WIS Notification Message, the Global Broker will record id of messages already published and will discard subsequent identitical (with the same message id) messages. This is the anti-loop feature of the Global Broker.
* During the pre-operational phase (2024), instead of discarding the message in the two situations above, processing will continue.
* When publishing a message to the local broker, the metrics ``wmo_wis2_gb_messages_published_total`` will be increased by 1. 
* All aboved defined metrics will be made avalaible on HTTPS endpoints that the Global Monitor will ingest from regularly.
* As a convention Global Broker centre-id will be ``tld-centre-name-globalbroker``. 
* The figure xxx provides an illustration of the workflow followed by a Global Broker when getting a message.

==== Global Cache

===== Technical considerations

* The Global Cache will contain copies of real-time and near real-time data designated as "core" within the WMO Unified Data Policy (Resolution 1).
* During the initial stages of the WIS2 pilot phase Global Cache instances will provide open access to their cached content. Access control mechanisms may be added later.
* A Global Cache instance will host data objects copied from NC/DCPCs. These are persisted as files.
* A Global Cache instance will publish notification messages advertising availability of the data objects it holds. The notification messages will follow the standard structure (see 4.3 	Notification message format and structure).
* A Global Cache instance will use the standard topic structure in their local message brokers (see WIS2 messages 4.4 Standard topic hierarchy).
* There will be multiple Global Cache instances to ensure highly available, low latency global provision of real-time and near real-time "core" data within WIS.
* Global Cache instances may attempt to download cacheable data objects from all originating centres with "cacheable" content. A Global Cache instance will also download data objects from other instances. This ensures the instance has full global coverage, mitigating where direct download from an originating centre is not possible.
* For full global coverage, a Global Cache instance will download Data Objects and discovery metadata records from other instances.
* Global Cache instance will operate independently of other Global Cache instances. Each Global Cache instance will hold a full copy of the cache – albeit that there may be small differences between Global Cache instances as "data availability" notification messages propagate through WIS to each Global Cache in turn. There is no formal ‘synchronisation’ between Global Cache instances.
* A Global Cache will store a full set of discovery metadata records. This is not an additional metadata catalogue that Data Consumers can search and browse – it provides a complete set of discovery metadata records to support populating a Global Discovery Catalogue instance.
* A Global Cache is designed to support real-time distribution of content. Data Consumers access data objects from a Global Cache instance by resolving the URL in a "data availability" notification message and downloading the file. 
* There is no requirement for a Global Cache to provide a "browse-able" interface to the files in its repository allowing Data Consumers to discover what content is available. However, a Global Cache may choose to provide such a capability (e.g., implemented as a "Web Accessible Folder", or WAF) along with adequate documentation for Data Consumers to understand how the capability works.

TODO: to be completed

===== Practices and procedures

The following procedures will be described here once validated through testing during the WIS2 pilot phase:
* Assigning a Global Cache to a NC or DCPC
* Lifecycle management of discovery metadata records stored in the Global Cache.

TODO: to be completed

==== Global Discovery Catalogue

===== Technical considerations

* The Global Discovery Catalogue provides Data Consumers with a mechanism to discover the Datasets of interest, as well as, how to interact with and find out more information about those Datasets.
* The Global Discovery Catalogue implements the OGC API – Records – Part 1: Core standard.
* The Global Discovery Catalogue advertises the availability of Datasets and how/where to access them or subscribe to updates, it does not advertise the availability of individual Data Objects that comprise a dataset (i.e., data files).
* A single Global Discovery Catalogue instance is sufficient for WIS2.
* Multiple Global Discovery Catalogue instances may be deployed for resilience.
* Global Discovery Catalogue instances operate independently of each other – each Global Discovery Catalogue instance will hold all discovery metadata records. There is no need to synchronise between Global Discovery Catalogue instances.
* A Global Discovery Catalogue is populated with discovery metadata records from a Global Cache instance – receiving messages about availability of discovery metadata records via a Global Broker.
* A Global Discovery Catalogue should connect to more than one Global Broker instance to ensure that no messages are lost in the event of a Global Broker failure. A Global Discovery Catalogue instance shall discard duplicate messages as needed.
* A Global Discovery Catalogue will validate discovery metadata records against the WMO Core Metadata Profile version 2 (WCMP2), discarding non-compliant records and raising an alert.
* A Global Discovery Catalogue will update discovery metadata records it receives to add links for subscription URLs at Global Broker instances.
* A Global Discovery Catalogue should applying faceting capability as specified in the cataloguing considerations of the WCMP2 specification as defined in OGC API - Records.
* A Global Discovery Catalogue shall provide human-readable Web pages with embedded markup using the schema.org vocabulary, thereby enabling search engines to crawl and index the content of the Global Discovery Catalogue. Consequently, Data Consumers should also be able to discover WIS content via third party search engines.
* A Global Discovery Catalogue shall periodically assess the discovery metadata provided by NCs and DCPCs against a set of key performance indicators (KPIs) in support of continuous improvement. Suggestions for improvement are shared with the originating NC or DCPC and their primary GISC.
* A Global Discovery Catalogue shall generate and store a zipfile of all WCMP2 records once a day, that shall be made be accessible via HTTP.
* A Global Discovery Catalogue shall then publish a WIS2 Notification Message on its centre-id's +metadata+ topic (i.e. `origin/a/wis2/centre-id/metadata`, where `centre-id` is the centre identifier of the Global Discovery Catalogue)`.

TODO: to be completed

===== Practices and procedures

The following procedures will be described here once validated through testing during the WIS2 pilot phase:

* Alerting originating NC or DCPC about malformed or non-compliant discovery metadata records
* Providing feedback to NC and DCPC about how to improve their discovery metadata
* Removing discovery metadata for a Dataset on request
* ‘Bootstrapping’ a Global Discovery Catalogue instance from the Global Cache

TODO: to be completed

==== Global Monitor

===== Technical Considerations
* WIS standardises how system performance and data availability metrics are published from WIS nodes and Global Services.
* For each type of Global Service, a set of standard metrics have been defined. Global Services will implement those metrics and provide an endpoint for those metrics to be fetched by the Global Monitor
* The Global Monitor will collect metrics as defined in the OpenMetrics standard.
* The Global Monitor will monitor the 'health' (i.e., performance) of WIS2 Node as well as Global Service instances.
* The Global Monitor will provide a Web-based ‘dashboard’ that displays the WIS system performance and data availability. The WIS Operations and Management team, in close collaboration with the Global Services will define the content of the dashboard. 
* The Global Monitor, through the metrics provided, will be able to detect issues. In this case, Global Monitor will publish a Notification Message in the monitoring topic, as define by the WIS Operations and Monitoring team.
TODO: to be completed
