=== 2.7 Implementation and operation of a Global Service

==== 2.7.1 Procedure for registering a new Global Service
The successful operation of WIS2 depends on a set of Global Services running well-managed IT environments with a very high level of reliability so that all WIS2 users and WIS2 Nodes are able to access and provide the data they need for their duties.

Depending on the nature of the Global Service, the following are the minimum capabilities needed to ensure that the level of service as a whole reaches 100% (or very close):

*	Three Global Brokers, with each Global Broker connected to at least two other Global Brokers;
*	Three Global Caches, with each Global Cache connected to at least two Global Brokers and capable of downloading data from all WIS2 Nodes providing core data;
*	Two Global Discovery Catalogues, with each Global Discovery Catalogue connected to at least one Global Broker;
* Two Global Monitors - each Global Monitor should scrape the metrics from all other Global Services

In addition to the above, WIS architecture can accommodate adding (or removing) Global Services. Candidate WIS centres should inform their WIS NFP and contact the WMO Secretariat to discuss their offer to provide a Global Service.

Running a Global Service is a significant commitment for a WIS centre. To maintain a very high level of service, each Global Service has a key role to play.

On receipt of an offer from a Member to operate a Global Service, the WMO Secretariat will suggest which Global Service the Member may provide to improve WIS2. This suggestion will be based on the current situation of WIS2 (such as the number of existing Global Brokers, whether an additional Global Cache is needed, and so forth).

The _Manual on WIS_, Volume II, the present Guide, and other available materials will help WIS centres decide how to proceed.

When a decision on how to proceed has been made, the WIS NFP will inform the WMO Secretariat of its preference. Depending on the type of Global Service, the WMO Secretariat will provide a checklist to the WIS centre so that the future Global Service can be included in WIS operations.

A WIS centre must commit to running the Global Service for a minimum of four years.

The WMO Secretariat and other Global Services will make the required changes to include the new Global Service in WIS operations.

==== 2.7.2 Performance management and monitoring of a Global Service

===== 2.7.2.1 Monitoring and metrics for WIS2 operations

The availability of data and the performance of system components within WIS2 are actively monitored by GISCs and the Global Monitor service to ensure proactive responses to incidents and effective capacity planning for future operations.

WIS2 requires that metrics are provided using OpenMetricsfootnote:[See OpenMetrics: https://openmetrics.io.] – the widely adopted, de-facto standardfootnote:[OpenMetrics is proposed as a draft standard within the Internet Engineering Task Force (IETF).] for transmitting cloud-native metrics at scale. Many commercial and open-source software components already come preconfigured to provide performance metrics using the OpenMetrics standard. Tools such as Prometheus and Grafana aggregate and visualize metrics provided in this format, making it simple to generate performance insights.

WIS2 Global Services (Global Brokers, Global Caches, and Global Discovery Catalogues) provide monitoring metrics about their respective service to Global Monitors.

There is no requirement for WIS2 Nodes to provide monitoring metrics. However their WIS2 interfaces may be queried remotely by Global Services, which can then provide metrics on the availability of WIS2 Nodes.

Metrics for WIS2 monitoring should follow the naming convention ``wmo_<program>_<name>``, where ``<program>`` is the name of the responsible WMO programme and ``<name>`` is the name of the metric. Examples of WIS2 metrics include:

  ``wmo_wis2_gc_downloaded_total``, and

  ``wmo_wis2_gb_messages_invalid_total``.

The full set of the WIS2 monitoring metrics is given in WMO: WIS2 Metric Hierarchy footnote:[See https://github.com/wmo-im/wis2-metric-hierarchy.]

===== 2.7.2.2 Service levels, performance indicators, and fair usage policies
* Each WIS centre operating a WIS2 Node is responsible for achieving the highest possible level of service based on its resources and capabilities.
* All Global Services, in particular Global Brokers and Global Caches, are collectively responsible for making WIS a reliable and efficient means of exchanging the data required for the operation of all WIS centres. The architecture provides a redundant solution where the failure of one component will not impact the overall level of service of WIS.
* Each Global Service should aim to achieve at least 99.5% availability of the service it provides. This is not a contractual target. It should be considered by the entity providing the Global Service as a guideline when designing and operating that service.
* A Global Broker:
** Should support a minimum of 200 WIS2 Nodes or Global Services;
** Should support a minimum of 1 000 subscribers;
** Should support the processing of a minimum of 10 000 messages per second.
* A Global Cache:
** Should support a minimum of 100 GB of data in the cache;
** Should support a minimum of 1 000 simultaneous downloads;
** Could limit the number of simultaneous connections from a user (known by its originating source IP) to five;
** Could limit the bandwidth usage of the service to 1 Gb/s.
* A Global Monitor:
** Should support a minimum of 50 metrics providers;
** Should support 200 simultaneous "access" to the dashboard;
** Could limit the bandwidth usage of the service to 100 Mb/s.
* A Global Discovery Catalogue:
** Should support a minimum of 20 000 metadata records;
** Should support a minimum of 50 requests per second to the API endpoint.

===== 2.7.2.3 Metrics for Global Services

In the following sections, and for each Global Service, a set of metrics is defined. Each Global Service will provide those metrics. They will then be ingested by the Global Monitor.

==== 2.7.3 Global Broker

===== 2.7.3.1 Technical considerations

* As detailed above, there will be at least three Global Brokers to ensure that messages within WIS2 are highly available and delivered globally with low latency.
* A Global Broker subscribes to messages from WIS2 Nodes and other Global Services. The Global Broker should aim to subscribe to all WIS centres. If this is not possible, the Global Broker should inform the WMO Secretariat so that the situation can be documented.
* Every WIS2 Node or Global Service must have subscriptions from at least two Global Brokers.
* For full global coverage, a Global Broker will subscribe to messages from at least two other Global Brokers.
* When subscribing to messages from WIS2 Nodes and other Global Services, a Global Broker must authenticate using the valid credentials managed by the WIS centre and available at WMO Secretariat.

* A Global Broker is built around two software components:
** An off the shelf broker implementing both MQTT 3.1.1 and MQTT 5.0 in a highly available setup, typically in a cluster mode. Tools such as EMQX, HiveMQ, VerneMQ, RabbitMQ (in its latest versions) are compliant with these requirements. The open source version of Mosquitto cannot be clustered and therefore should not be used as part of a Global Broker.
** Additional features, including anti-loop detection, notification message format compliance, validation of the published topic, and metrics provision.

* When receiving a message from a local WIS centre broker or a Global Service broker, the metric ``wmo_wis2_gb_messages_received_total`` will be increased by 1.
* A Global Broker will check if a discovery metadata record exists corresponding to the topic on which a message has been published. If there is no corresponding discovery metadata record, the Global Broker will discard non-compliant messages and will raise an alert. The metric ``wmo_wis2_gb_messages_no_metadata_total`` will be increased by 1. The Global Broker should not request information from a Global Discovery Catalogue for each notification message but should keep a cache of all valid topics for every ``centre-id``.
* A Global Broker will check that the topic on which the message is received is valid. If the topic is invalid, the Global Broker will discard non-compliant messages and will raise an alert. The metric ``wmo_wis2_gb_invalid_topic_total`` will be increased by 1.
* During the pre-operational phase (2024), a Global Broker will not discard the message but instead will send a message on the `monitor` topic hierarchy to inform the originating centre and its GISC.
* A Global Broker will validate notification messages against the standard format (see _Manual on WIS_, Volume II – Appendix E. WIS2 Notification Message), discarding non-compliant messages and raising an alert. The metric ``wmo_wis2_gb_invalid_format_total`` will be increased by 1.
* A Global Broker will republish a message only once. It will record the message identifier (``id``) (as defined in the WIS2 Notification Message) of messages already published and will discard subsequent identical messages (those with the same message ``id``). This is the anti-loop feature of the Global Broker.
* When publishing a message to the local broker, the metric ``wmo_wis2_gb_messages_published_total`` will be increased by 1.
* A Global Broker will update its metrics at least every 60 seconds.
* A Global Broker should not reset its metrics counts.
* All above-defined metrics will be made available on HTTPS endpoints that the Global Monitor will ingest from regularly.
* As a convention, the Global Broker centre-id will be ``tld-{centre-name}-global-broker``.
* A Global Broker should operate with a fixed IP address so that WIS2 Nodes can permit access to download resources based on IP address filtering. A Global Broker should also operate with a publicly resolvable Domain Name System (DNS) name pointing to that IP address. The WMO Secretariat must be informed of the IP address and/or hostname and any subsequent changes.

==== 2.7.4 Global Cache

In WIS2, Global Caches provide access to WMO core data for data consumers. This allows data providers to restrict access to their systems to Global Services, and it reduces the need for them to provide high bandwidth and low latency access to their data. Global Caches operate in a way that is transparent to end users in that they resend notification messages from data providers. These messages are updated to point to copies of the original data held in the Global Cache data store. Global Caches also resend notification messages from data providers for core data that are not stored in the Global Cache, such as when the originator specifies in the notification message that a certain dataset should not be cached. In these cases, the notification messages remain unchanged and point to the original source. Data consumers should subscribe to the notification messages from Global Caches instead of the notification messages from data providers for WMO core data. When data consumers receive a notification message, they should follow the URLs from that message, which either point to a Global Cache which has a copy of the data, or – in case of uncached content – point to the original source.

===== 2.7.4.1 Technical considerations

* A Global Cache is built around three software components:
** A highly available data server allowing data consumers to download cache resources with high bandwidth and low latency;
** A Message Broker implementing both MQTTv3.1.1 and MQTTv5 to publish notification messages about resources that are available from the Global Cache;
** A cache management system implementing the features needed to connect to the WIS ecosystem, receive data from WIS2 Nodes and other Global Caches, store the data on the data server and manage the content of the cache (expiration of data, deduplication, and so forth).
* A Global Cache will aim to contain copies of real-time and near real-time data designated as "core" within the WMO Unified Data Policy (Resolution 1 (Cg-Ext(2021))).
* A Global Cache will host data objects copied from NCs/DCPCs.
* A Global Cache will publish notification messages advertising the availability of the data objects it holds. The notification messages will follow the standard structure (see _Manual on WIS_, Volume II -Appendix E. WIS2 Notification Message).
* A Global Cache will use the standard topic structure in its local Message Brokers (see _Manual on WIS_, Volume II - Appendix D. WIS2 Topic Hierarchy).
* A Global Cache will publish to the topic ``cache/a/wis2/...``.
* There will be multiple Global Cache to ensure the highly available, low-latency global provision of real-time and near-real-time core data within WIS2.
* There will be multiple Global Caches that may attempt to download cacheable data objects from all originating centres with cacheable content. A Global Cache will also download data objects from other Global Caches. This will ensure that each Global Cache has full global coverage, even when direct download from an originating centre is not possible.
* Global Caches will operate independently of one another. Each Global Cache will hold a full copy of the cache – although there may be small differences between the various Global Caches as data availability notification messages propagate through WIS to each one. There is no formal synchronization between Global Caches.
* A Global Cache will temporarily cache all resources published on the ``metadata`` topic. A Global Discovery Catalogue will subscribe to notifications about the publication of new or updated metadata, download the metadata record from the Global Cache and insert it into the catalogue. A Global Discovery Catalogue will also publish a metadata record archive each day containing the complete content of the catalogue and advertise its availability with a notification message. This resource will also be cached by a Global Cache.
* A Global Cache is designed to support real-time content distribution. Data consumers access data objects from a Global Cache instance by resolving the URL in a data availability notification message and downloading the file to which the URL points. Only by checking the URL, is it transparent to the data consumers from which Global Cache they are downloading the data. There is no need to download the same data object from multiple Global Caches. The data id contained within notification messages is used by data consumers and Global Services to detect such duplicates.
* There is no requirement for a Global Cache to provide a browsable interface to the files in its repository in order to allow data consumers to discover what content is available. However, a Global Cache may choose to provide such a capability (for example, implemented as a WAF), along with documentation to inform data consumers of how the capability works.
* The default behaviour for a Global Cache is to cache all data published under the ``origin/a/wis2/{centre-id}/data/core`` topic. A data publisher may indicate that data should not be cached by adding the ``"cache": false`` assertion in the WIS2 Notification Message.
* A Global Cache may decide not to cache data, for example, if the data are considered too large, or if a WIS2 Node publishes an excessive number of small files. If a Global Cache decides not to cache data, it should behave as though the cache property is set to false and send a message on the ``monitor`` topic hierarchy to inform the originating centre and its GISC. The Global Cache operator should work with the originating WIS2 Node and its GISC to remedy this issue.
* If core data are not cached on a Global Cache (that is, if the data are flagged as ``"cache": false`` or if the Global Cache decides not to cache these data), the Global Cache shall nevertheless republish the WIS2 Notification Message to the ``cache/a/wis2/...`` topic. In this case, the message id will be changed, and the rest of the message will not be modified.
* A Global Cache should operate with a fixed IP address so that WIS2 Nodes can permit access to download resources based on IP address filtering. A Global Cache should also operate with a publicly resolvable DNS name pointing to that IP address. The WMO Secretariat must be informed of the IP address and/or hostname, and any subsequent changes.
* A Global Cache should validate the integrity of the resources it caches and only accept data that match the integrity value from the WIS2 Notification Message. If the WIS2 Notification Message does not contain an integrity value, the Global Cache should accept the data as valid. In this case, the Global Cache may add an integrity value to the message it republishes.
* A Global Cache will provide the ``properties.global-cache`` property (with its centre identifier as the value) in notifications published to ``cache/a/wis2/{centre-id}`` for data that it caches.
* A Global Cache will update its metrics at least every 60 seconds.
* A Global Cache should not reset its metrics counts.
* As a convention, the Global Cache centre-id will be ``tld-{centre-name}-global-cache``.

===== 2.7.4.2 Practices and procedures

* A Global Cache shall subscribe to the topics `+origin/a/wis2/#+` and `+cache/a/wis2/#+`.
* A Global Cache shall ignore all messages received on the topics ``++origin/a/wis2/+/data/recommended/#++`` and ``++cache/a/wis2/+/data/recommended/#++``footnote:[It is also technically possible to filter recommended data by using a wildcard subscriptions such as ``++origin/a/wis2/+/data/core/#++``. However, avoiding wildcard subscription is generally considered good practice as it limits the burden of the broker operated by Global Brokers.]
* A Global Cache shall retain the data and metadata it receives for a minimum of 24 hours. Requirements relating to varying retention times for different types of data may be added later.
* For messages received on the topic ``++origin/a/+/data/core/#++`` or ``++cache/a/+/data/core/#++``, a Global Cache shall:
** If the message contains the property ``"properties.cache": false``,
*** Republish the message at topic ``cache/a/wis2/...``, matching ``+/a/wis2/...`` where the original message has been received, after having updated the id of the message.
** Else
*** Maintain a list of ``data_id`` values that have already been downloaded;
*** Verify whether the message points to new data (new ``data_id`` and inspecting the link ``rel`` attribute is ``canonical``) or updated data (known ``data_id``, more recent ``pubtime`` and inspecting the link ``rel`` attribute is ``updated``);
*** If the message is new or updated:
**** Download only new or updated data from the ``href`` or extract the data from the message content;
**** If the message contains an integrity value for the data, verify the integrity of the data;
**** If data is downloaded successfully,  move the data to the HTTP endpoint of the Global Cache;
**** Wait until the data becomes available at the endpoint;
**** Modify the message identifier and the canonical link's ``href`` of the received message and leave all other fields untouched;
**** Republish the modified message to topic ``cache/a/wis2/...`` ,matching the ``+/a/wis2/...`` where the original message has been received;
**** The metric ``wmo_wis2_gc_downloaded_total`` will be increased by 1; The metric ``wmo_wis2_gc_dataserver_last_download_timestamp_seconds`` will be updated with the timestamp (in seconds) of the last successful download from the WIS2 Node or Global Cache;
*** Else
**** Drop the messages for data already present in the Global Cache.

* If the Global Cache is not able to download the data, the metric ``wmo_wis2_gc_downloaded_error_total`` will be increased by 1.
* A Global Cache shall provide the metric defined in this Guide at an HTTP endpoint.
* A Global Cache should make sure that data are downloaded in parallel and that downloads are not blocking each other.

* The metric ``wmo_wis2_gc_dataserver_status_flag`` will reflect the status of the connection to the download endpoint of the centre. Its value will be 1 when the endpoint is up and 0 otherwise.
* The metric ``wmo_wis2_gc_last_metadata_timestamp_seconds`` will reflect the datetime (as a timestamp, the number of seconds since the UNIX epoch) of the last metadata resource processed by a given centre.

==== 2.7.5 Global Discovery Catalogue

===== 2.7.5.1 Technical considerations

* The Global Discovery Catalogue provides data consumers with a mechanism for discovering and searching for datasets of interest as well as learning how to interact with and find out more information about those datasets.
* The Global Discovery Catalogue implements the OGC API – Records – Part 1: Core standardfootnote:[See OGC-API Records - Part 1 https://docs.ogc.org/DRAFTS/20-004.html.], adhering to the following conformance classes and their dependencies:
** Searchable Catalog (Deployment);
** Searchable Catalog - Sorting (Deployment);
** Searchable Catalog - Filtering (Deployment);
** JSON (Building Block);
** HTML (Building Block).
* The Global Discovery Catalogue will make discovery metadata available via the collection identifier `wis2-discovery-metadata`.
* The Global Discovery Catalogue advertises the availability of datasets and how to access them or subscribe to updates.
* The Global Discovery Catalogue does not advertise or list the availability of individual data objects that comprise a dataset (that is, data files).
* A single Global Discovery Catalogue is sufficient for WIS2.
* Multiple Global Discovery Catalogues may be deployed for resilience.
* Global Discovery Catalogues operate independently of each other; each Global Discovery Catalogue holds all discovery metadata records.  Global Discovery Catalogues do not need to synchronize with each other.
* A Global Discovery Catalogue is populated with discovery metadata records from a Global Cache  and receives messages about the availability of discovery metadata records via a Global Broker.
** The subscription topic shall be ``++cache/a/wis2/+/metadata/#++``.
* A Global Discovery Catalogue should connect to and subscribe to more than one Global Broker to ensure that no messages are lost in the event of a Global Broker failure. A Global Discovery Catalogue will discard duplicate messages as needed.
* A Global Discovery Catalogue will verify that a discovery metadata record identifier’s centre-id token (see Manual on WIS, Volume II – Appendix F. WMO Core Metadata Profile (Version 2)) matches the centre-id level of the topic from which it was published (see Manual on WIS, Volume II – Appendix D. WIS2 Topic Hierarchy) to ensure that discovery metadata are published by the authoritative organization.
* A Global Discovery Catalogue will validate discovery metadata records against the WCMP2. Valid WCMP2 records will be ingested into the catalogue. Invalid or malformed records will be discarded and reported to the Global Monitor against the centre-id associated with the discovery metadata record.
* A Global Discovery Catalogue will only update discovery metadata records to replace links for dataset subscription and notification (origin), with their equivalent links for subscription at Global Brokers (cache).
* A Global Discovery Catalogue will periodically assess discovery metadata provided by NCs and DCPCs against a set of key performance indicators (KPIs) in support of continuous improvement. Suggestions for improvement will be reported to the Global Monitor against the centre identifier associated with the discovery metadata record.
* A Global Discovery Catalogue will remove discovery metadata that are marked for deletion as specified in the data notification message.
* A Global Discovery Catalogue should apply faceting capability as specified in the cataloguing considerations of the WCMP2 specification, as defined in OGC API - Records.
* A Global Discovery Catalogue will provide human-readable web pages with embedded markup using the schema.org vocabulary, thereby enabling search engines to crawl and index its content. Consequently, data consumers should be able to discover WIS content via third party search engines.
* A Global Discovery Catalogue will generate and store a zip file of all WCMP2 records once a day; this file will be made be accessible via HTTP. The zipfile will include a directory named after the centre-id of the Global Discovery Catalogue containing all WCMP2 records.
* A Global Discovery Catalogue will publish a WIS2 Notification Message of its zip file of all WCMP2 records on its centre-id's +metadata+ topic (for example, `origin/a/wis2/centre-id/metadata`, where `centre-id` is the centre identifier of the Global Discovery Catalogue).
* A Global Discovery Catalogue will generate metrics on a daily basis for the following:
** ``wmo_wis2_gdc_core_total`` (foreach centre identifier)
** ``wmo_wis2_gdc_recommended_total`` (foreach centre identifier)
** ``wmo_wis2_gdc_earth_system_discipline_total`` (foreach Earth system discipline per centre identifier)
** ``wmo_wis2_gdc_kpi_percentage_total`` (foreach discovery metadata record per centre identifier)
** ``wmo_wis2_gdc_kpi_percentage_average`` (foreach centre identifier)
** ``wmo_wis2_gdc_kpi_percentage_over80_total`` (foreach centre identifier)
* A Global Discovery Catalogue may initialize itself (cold start) from a zip file of all WCMP2 records published.
* As a convention, a Global Discovery Catalogue's centre-id will be ``tld-{centre-name}-global-discovery-catalogue``.

===== 2.7.5.2 Global Discovery Catalogue reference implementation: wis2-gdc

To provide a Global Discovery Catalogue, Members may use whichever software components they consider most appropriate to comply with the WIS2 technical regulations.

To assist Members in participating in WIS2, a free and open-source Global Discovery Catalogue reference implementation, wis2-gdc, is available for download and use. wis2-gdc builds on mature and robust free and open-source software components that are widely adopted for operational use.

wis2-gdc provides the functionality required for the Global Discovery Catalogue, including the following technical functions:

* Discovery metadata subscription and publication from the Global Broker;
* Discovery metadata download from the Global Cache;
* Discovery metadata validation, ingest and publication;
* WCMP2 compliance;
* Quality assessment (KPIs);
* OGC API - Records - Part 1: Core compliance;
* Metrics reporting;
* Implementation of metrics.

wis2-gdc is managed as a free and open source project. Source code, issue tracking and discussions are hosted openly on GitHub: https://github.com/wmo-im/wis2-gdc.

==== 2.7.6 Global Monitor

===== 2.7.6.1 Technical considerations
* WIS standardizes how system performance and data availability metrics are published from WIS2 Nodes and Global Services.
* For each type of Global Service, a set of standard metrics has been defined. Global Services will implement and provide an endpoint for those metrics to be scraped by the Global Monitor.
* The Global Monitor will collect metrics as defined in the OpenMetrics standard.
* The Global Monitor will monitor the "health" (that is, the performance) of components at NCs/DCPCs, as well as Global Services.
* The Global Monitor will provide a web-based dashboard that displays the WIS2 system performance and data availability.
* A Global Monitor will update its metrics at least every 60 seconds.
* A Global Monitor should not reset its metrics counts.
* As a convention, the Global Monitor centre-id will be ``tld-{centre-name}-global-monitor``.
* The main task of the Global Monitor will be to regularly query the metrics provided by the relevant WIS2 entities, aggregate and process the data and then provide the results to the end user in a suitable presentation.
