=== Implementation and operation of a WIS2 Node

==== Practices and procedures

===== Registration and decommissioning of a WIS2 Node

Registration and decomissionig of WIS2 Nodes must be approved by the PR for the centre registering or decomissioning a WIS2 Node.

WMO Secretariat will operate a WIS2 register. The registration of a WIS2 Node involves the following steps:

* Request hosting a WIS2 Node: A request for hosting a WIS2 Node shall be put forward by the Permanent Representative of the country of the WIS2 Node host centre, or, in the case of international organizations, by either the Permanent Representative (PR) of the country where the WIS2 Node host centre is located or the president of the relevant organization in case of WMO partner or programme designated as DCPC.
* Assign a centre-id: The centre identifier (`centre-id`) is an acronym as specified by the member and endorsed by the PR of the country and WMO. It is a single identifier comprised of a top level domain (TLD) and centre name, and represents the data publisher, distributor or issuing centre of a given dataset or data product/granule (see the Topic Hierarchy Manual on WIS Vol II).
* Complete the WIS2 Register: The WIS National Focal Point shall complete the WIS2 Register operated by the WMO Secretariat 
* WIS2 Node assessment: the principal GISC verifies that the WIS2 Node is compliant with WIS2 requirements. The assessment includes: 
  - the verification of the compliance of the WIS2 Topic Hierarchy (WTH) used by the centre with the WIS2 Topic Hierarchy. 
  - verification of compliance of the Notification Message with the specifications.
  - verification that the download link is using HTTPS which is a preference for WIS2.

Upon completion of this verification, and confirmation that it satisfies all conditions for operating a WIS2 Node, GISC notifies WMO and confirms that this centre identifier can be added to WIS2.

* Communicate details to the Global services: WMO Secretariat provides the WIS2 Node details to the Global Brokers to subscribe to the WIS2 Node.

A diagram of the process of registering a WIS2 Node is presented in Annex. TODO: diagram?

===== Registration and removal of a dataset

Procedure for PR Approved WIS2 Node Registration is to create a centre identifier based on naming convention `ab-domain-nodename`.  Where `ab` is the the IANA Top Level Domain (TLD) code, domain is the organization's domain name for the main website, and nodename (optional) is descriptive of the purpose of the WIS2 Node (for example a node for a type of data or programme of the data e.g. climate, aviation, etc.) when the organization is hosting multiple WIS2 Nodes. A sample centre identifier is `ab-myorg-climate`.  In addition to the centre identifier the registering organization should also provide the broker endpoints.  Once centre identifier and broker endpoints are provided and entered into the WIS2 Node register, the WMO Secretariat will contact the GISC for the organization's country and request the GISC to verify the correctness of the provided information.  The GISC will request the centre produce a test message with associated files for download.  The GISC should use a test MQTT client to verify the notification message is correct and the download links are functional.  The GISC notifies the Centre of the results of the checks and if all are good, requests the Centre to provide metadata when the dataset is ready.  When metadata is proivided the GISC informs the WMO Secretariat that the new centre identifier is ready and requests it be added to WIS2.

In the case of NCs, the procedure for PR approved decomissioning of a WIS2 Node is the PR (or designate) will notify the WMO Secretariat of the decomissioning of the WIS2 Node. In the case of DCPCs, the sponsor (i.e., Regional Association or WMO Programme) is the Programme Chair or Regional Information Management Chair shall approve the decommissioning and notify the WMO Secretariat of the decomissioning of the WIS2 Node. Where possible, a 30 day notice period should be provided prior to the decomissioning and information on if the data from the Node will also be decomissioned or if it is available via another WIS2 Node or method.  The WMO Secretariat will notify the GISC for the country and the Global Service Providers of the date of the WIS2 Node decomissioning.  

NC/DCPCs operators decomissioning a WIS2 Node shall ensure that obligations relating to data sharing within WIS continue to be met after the WIS2 Node is decommissioned, for example, by migrating these data sharing obligations to another WIS2 Node. In the case of DCPCs, this may mean the WIS2 Node responsibilities shift from one member to another and in the case these details should be included in the decomissioning notice to the WMO Serectariat.

A Data Producer publishes data via a WIS2 Node in accordance with the WIS2 Topic Hierarchy by creating a discovery metadata record, making it available for download, and publishing a notification of its availability (see how to publish data notifications TODO CROSSREF).  Global Brokers then subscribe to the relevant topic, receive the notification message, and then validate, ingest, and publish the associated dataset record.

All data shared in WIS2 must include metadata compliant with the metadata requriements described below.  Data providers must be approved by their PR (or designate such as the member's WIS Focal Point) to ensure quality metadata will be provied along with the data.

An organization ready to publish a new dataset should contact the WMO Secretariat with the approval of their PR (or designate) to The WMO Secretariat.  The WMO Secretariat will contact the GISC for the organizaiton with the new (meta)data.  The GISC will work with a Global Discovery Catalogue to verify the metadata.  the GDC will publish a report indicating errors and/or potential improvements (based on discovery metadata KPIs). The GISC should work with the data publisher to remedy issues and incporate suggestions for improvement.  

In addition, the data publisher's affiliated GISC conduct a systematic review of what's being published to make sure everything is functional.

===== Connecting with Global Services

Once a WIS2 Node has been verified by a GISC and endpoints and metadata are available, the WMO Secretariat provides the new centre identifier to the Global Brokers and requests they subscribe to the new broker endpoint.  The Global Broker will recieve the data based on their topic subscriptions.  The Global Caches download and cache the metadata (and data where applicable for core datasets).

Once a GISC, in partnership with a Global Data Catalogue, verifies the metadata for a new dataset, the WMO Secretariat will be notified of the availability of the new dataset.  The WMO Seretariat will then notify the Global Borkers and Global Caches of the addition of new data to the WIS system.


==== Publishing data, discovery metadata, and notification messages


===== Discovery metadata

Discovery metadata shall be encoded according to the WMO Core Metadata Profile version 2 (WCMP2).

Discovery metadata may be published one of two ways. The simplest method is to encode the discovery metadata record as a file and publish it to an HTTP server. The URL of this file is included in the notification message advertising the availability of new metadata. Alternatively, a data publisher may choose to host a local catalogue themselves, enabling them to share discovery metadata records through an API (e.g., OGC API - Records). In this case, the URL used in the notification message will refer to the API endpoint identifying the specific discovery metadata record (e.g., an item as part of their discovery metadata catalogue).   

These discovery metadata records are then propagated through the Global Service components into to the Global Discovery Catalogue where Data Consumers can search and browse for datasets of interest.

Discovery metadata must be published before data is published to WIS2.

TODO: to be completed

===== Notification messages

There is no requirement for an NC/DCPC to publish "data availability" notification messages relating to infrequently changing datasets, such as a data archive, especially where the user community have no requirement to be instantly updated about changes to a dataset (e.g., the addition of new records into a climate observation archive). Data publishers should note that without providing notification messages their data will not be copied into the Global Cache. However, since the Global Cache only holds real-time (or near real-time) datasets, this is not a concern for data publishers with infrequently changing datasets.

TODO: to be completed

===== Data

WIS2 provides the "plumbing" for data sharing within the WMO community, but it defines neither which data to share, nor how that data should be encoded. WIS Centres need to evaluate WMO Programme requirements and the WMO Unified Data Policy to determine which datasets should be made available through WIS.

WMO Technical Regulations may require that data is encoded in particular formats. For example: synoptic observations should be encoded in BUFR. The Manual on Codes (WMO No. 306) provides details of data formats formally approved for use in WMO. 

However, Technical Regulations don’t cover all data sharing requirements. In such cases, data publishers should select data formats that are widely adopted and understood in their target user community. 

WIS2 does not require the use of specific file-naming conventions. Where communities commonly use file-naming conventions (e.g., with embedded metadata), data publishers should ensure that adequate documentation is provided to users. data publishers cannot assume that users will understand (or respect) their file-naming rules – many Data Consumers will simply treat the filename as an opaque string.

Data publishers also have choices about how they publish data.

As a minimum, data publishers may publish data objects (e.g., the atomic bits of data that comprise a dataset) as files using a Web server (HTTP protocol) or FTP server (FTP protocol), using secure communications (e.g., HTTPS/SFTP). As each data object is published, a notification message should also be published to a topic in a message broker (see 4.3 Notification message format and structure, and WIS2 messages 4.4 WIS2 Topic Hierarchy TODO: CROSSREF).

A dataset (for example, a collection of climate model runs) may comprise thousands or more files. A data publisher may choose to provide users with a mechanism to browse through the set of files, enabling them to identify those which are relevant to them. Examples of such mechanisms include, but are not limited to:

* Web Accessible Folders (WAF): a Web-based folder structure listing the data object files by name
* SpatioTemporal Asset Catalog (STAC): a community standard based on GeoJSON to describe geospatial data files which can be easily indexed, browsed, and accessed. Free and open sourcr tools  tools present STAC records (one for each data object file) through a Web-based, browse-able user interface

WAFs and STAC are provided to illustrate options. There is no requirement for a data publisher to provide any such browse-able user interface to their data.

Increasingly, interactive Web APIs are being used to provide access to datasets. Although requiring a little more sophistication to implement, a Web API provides significant advantages:

* Data Consumers can select and download only the parts of a dataset that they need – providing them will a smaller dataset subset to work with and reducing the burden on the data publisher’s network infrastructure.
* Data Consumers are insulated from the complexities of how a data publisher chooses to persist their data. The Web API can provide access to datasets in a way that is easy for users to understand.
* A Web API may allow Data Consumers to download data in their preferred file format or encoding. 

WIS-TECHSPEC-2 states:

    4.3.3 URLs provided for accessing core data, as defined in WMO Unified Data Policy (Res. 1), and discovery metadata shall be directly resolvable, i.e., data or discovery metadata can be downloaded simply by resolving the given URL without further action, such as populating elements of an API, is required.

When using a Web API to publish "core" data, the URL included in the data availability notification message must be directly resolvable, i.e., the Data Consumer must not be required to complete any additional fields in the API request. This can be achieved by identifying the data object in the URL. A Data Consumer or a Global Cache instance can simply resolve the URL to download the data object regardless of the manner in which it is made available.  

WIS2 seeks to leverage the experience of data publishers who have been using Web APIs to serve their communities.

First, interactive Web APIs should be self-describing. A Data Consumer should not need to know, apriori, how to make requests from a Web API. They should be able to discover this information from the Web API endpoint itself – even if this is just a link to a documentation page they need to read.

Second, we recommend that Web APIs are compliant with OpenAPI version 3 or later. OpenAPI provides a standardised mechanism to describe the API. Effectively, OpenAPI provides metadata that describes the Web API endpoint. Tooling (free and, commercial, etc.) is widely available that can read this metadata and automatically generate client applications to query the Web API.

Third, the Open Geospatial Consortium (OGC) have developed a suite of APIs (called "OGC APIs") that are designed specifically to provide APIs for geospatial data workflows (discovery, vizualisation, access, processing/exploitation) – all of which build on OpenAPI v3. Among these, OGC API – Environmental Data Retrieval (EDR), OGC API – Features, and OGC API - Coverages are considered particularly useful. Because these are open standards, there is an ever-growing suite of software implementations (both free and proprietary) that support them. We recommend that data publishers assess these open-standard API specifications to determine their suitability to for publishing their datasets using APIs.

Finally, we are increasingly concerned with providing access to very large datasets. The OGC has published a series of informative blogs on the subject of cloud-native geospatial data sharing. These are listed among in section 11.4.2 Informative References TODO PROPER CROSSREF.

====== Publication and topic selection

When publishing a dataset, a data publisher selects a given topic according to the WIS Topic Hierarchy.  Given the multidisciplinary nature of some data, a data publisher must select a single topic for publication purposes, and always uses WCMP2 discovery metadata to provide a fulsome description of their dataset and its relevance to additional disciplines.

Metadata is the method by which datasets are ultimately made available in the WIS2 system.  The goal is for data providers who have PR authorization to have a lightweight method to provide their datasets to WIS.  With this goal in mind, there are several acceptable methods to publish metadata:  

- Option 1: deploy a WIS2 node  
- Option 2: a MQTT broker and HTTP server  
- Option 3: a bilateral agreemnt for another organization to publish metadata publication on behalf of the data provider (potential organizations providing this service are GISCs and NMHS or potentional through a WIS2 portal in the future). 

For infrequently updated datasets the following process should be followed:  

- Publish initial metadata  
- Publish update metadata
- Data update notification: normal notification message with `property.cache=false`

===== Use of the "experimental" topic  

The "experimental" topic is necessary for the WIS2 pre-operational phase and future pre-operational data exchange in test mode.

The experimental topic sits under domain (level 8), e.g. ...weather/experimental. Data publishers can can extend the experimental branch with sub-topics as they deem appropriate.  

Data consumers must not assume that experimental topics will be durable (i.e., they may change or be removed).  

==== Performance management

===== Service levels and performance indicators

A WIS2 Node must be able to:  

- Publish datasets and compliant metadata and discovery metadata  
  * Publish metadata to the Global Data Catalogue
  * Publish core data to the Global Cache
  * Publish data for consumer access
  * Publish data embedded in a message (i.e., CAP warnings)
  * Receive metadata publication errors from the Global Data Catalogue  
  * Provide metadata with topics to Global Brokers

===== Provision of system performance metrics

WIS2 Nodes should provide annual performance metrics to their GISC.

If contacted by the Global Montior via GISC for a performance issue, the WIS2 Node should provide metrics to the GISC and Global Monitor when service is restored to indicate resolution of the issue.

==== WIS2 Node reference implementation: wis2box

To provide a WIS2 Node, members may use whichever software components they consider most appropriate to comply with WIS2 Technical Regulations.

To assist Members participate in WIS2, a free and open-source Reference Implementation is available for use.  WIS2 in a box (wis2box) implements the requirements of a WIS2 Node in as well as additional enhancements. wis2box builds on mature and robust free and open-source software components that are widely adopted for operational use.

wis2box provides functionality required for both data publisher and data consumer roles. It provides the following technical functions:

* Configuration, generation and publication of data (real-time or archive) and metadata to WIS2, compliant to WIS2 Node requirements
* MQTT Message Broker and notification message publication (Subscribe)
* HTTP object storage and raw data access (Download)
* Station metadata curation / editing tools (user interface)
* Discovery metadata curation / editing tools (user interface)
* Data entry tools (user interfaces)
* OGC API server, providing dynamic APIs for discovery, access, visualization and processing functionality (APIs)
* Extensible data "pipelines", allowing for transformation, processing and publishing of additional data types
* Provision of system performance and data availability metrics 
* Access control for recommended data publication, as required
* Subscription to notifications and and download of WIS data from Global Services 
* Modular design, allowing for extending to meet additional requirements or integrate with existing data management systems

Project documentation can be found at https://docs.wis2box.wis.wmo.int

wis2box is managed as a free and open source project.  Source code, issue tracking and discussions are hosted in the open on GitHub: https://docs.wis2box.wis.wmo.int.
