=== 2.1 WIS2 architecture

WIS2 is a federated system of systems based on web architecture and open standards, comprising many WIS2 Nodes, for publishing data and Global Services that enable fault tolerant, highly available, low-latency data distribution.

NCs, DCPCs, and GISCs are all types of WIS centres.

NCs and DCPCs operate WIS2 Nodes.

GISCs coordinate the operation of WIS within their area of responsibility (AoR) and ensure the smooth operation of the WIS2 system.

A WIS centre may also operate one or more Global Services.

WIS centres shall comply with the technical regulations defined in the _Manual on WIS_, Volume II.

=== 2.2 Roles in WIS2

When describing the functions of WIS2, there are four roles to consider:

. Data publisher;
. Global coordinator;
. Global Service operator;
. Data consumer.

These roles are outlined below.

==== 2.2.1 Data publisher
* This role is fulfilled by NCs and DCPCs.
* Data publishers operate a WIS2 Node to share their data within the WIS2 ecosystem.
* Data publishers manage, curate, and provide access to one or more datasets.
* For each dataset, a data publisher provides:
  i) Discovery metadata to describe the dataset and provide details on how it can be accessed and under what conditions;
  ii) An API or web service to access or interact with the dataset;
  iii) Notification messages advertising the availability of new data and metadata.

==== 2.2.2 Global coordinator 
* This role is exclusive to GISCs.
* All GISCs supporting WMO Members in their AoR fulfil their data sharing obligations via WIS2.

==== 2.2.3 Global Service operator
* To ensure highly available global data exchange, a WIS centre may operate one or more Global Services: 
  i)	The Global Discovery Catalogue enables users to search all datasets provided by data publishers and discover where and how to interact with those datasets (for example, to subscribe to updates, to access/download/visualize data, to access more detailed information about the dataset);
  ii)	A Global Broker provides highly available messaging services through which users may subscribe to notifications about all datasets provided by data publishers;
  iii)	A Global Cache provides a highly available download service for cached copies of core data downloaded from data publishers’ web services;
  iv)	A Global Monitor gathers and displays system performance, data availability, and other metrics from all WIS2 Nodes and Global Services;
  v)	A Global Replay provides access and subscription to past WIS Notification Messages.

==== 2.2.4 Data consumer
* This role represents anyone wanting to find, access, and use data from WIS2. Examples include NMHSs, government agencies, research institutions, private sector organizations, and so forth.
* Data consumers search or browse a Global Discovery Catalogue (or another search engine) to discover the datasets that meet their needs ("datasets of interest").
*	Data consumers subscribe via a Global Broker to receive notification messages about the availability of data or metadata associated with their datasets of interest.
*	Data consumers determine whether the data or metadata referenced in the notification messages are required.
*	Data consumers download data from a Global Cache or WIS2 Node.

=== 2.3 WIS2 specifications

Leveraging existing open standards, WIS2 defines the following specifications in support of publication, subscription, notification and discovery:

.WIS2 specifications
|===
|Specification|Granularity|Primary WIS2 Component(s)

|WMO Core Metadata Profile 2 (WCMP2)
|Datasets
|Global Discovery Catalogue

|WIS2 Topic Hierarchy (WTH)
|Dataset granules
|Global Broker, WIS2 Nodes

|WIS2 Notification Message (WNM)
|Dataset metadata, dataset granules
|Global Broker, Global Replay, WIS2 Nodes

|===

Refer to the _Manual on WIS_, Volume II for details.

=== 2.4 WIS2 Components

// TODO: add refs to other parts of the Guide describing these components

==== 2.4.1 WIS2 Node
* WIS2 Nodes are central to WIS2. They are operated by NCs and DCPCs to publish their core and recommended data.
* WIS2 adopts web technologies and open standards, enabling WIS2 Nodes to be implemented using freely available software components and common industry practices.
* WIS2 Nodes publish data as files on a web server or using an interactive web service.
* WIS2 Nodes describe the data they publish using discovery metadata. See the _Manual on WIS_, Volume II, Appendix F. WMO Core Metadata Profile (Version 2).
* WIS2 Nodes generate notification messages advertising the availability of new data. These notification messages are published to a Message Broker. The WIS2 Topic Hierarchy is used to ensure that all WIS2 Nodes publish to consistent topics. The information in the notification message tells the data consumer the location from which to download the data. Notification messages are also used to inform data consumers of the availability of discovery metadata. See the Manual on WIS, Volume II, Appendix D. WIS2 Topic Hierarchy and Appendix E. WIS2 Notification Message.
* WIS2 Nodes may control access to the data they publish. Global Services operate with fixed IP addresses, enabling WIS2 Nodes to easily distinguish their requests.

==== 2.4.2 Global Broker
* WIS2 incorporates several Global Brokers, ensuring the highly resilient distribution of notification messages across the globe.
* A Global Broker subscribes to the Message Broker operated by each WIS2 Node and republishes notification messages.
* A Global Broker subscribes to notifications from other Global Brokers to ensure that it receives a copy of all notification messages.
* A Global Broker republishes notification messages from every WIS2 Node and Global Service.
* A Global Broker operates a highly available, high-performance Message Broker.
* A Global Broker uses the WIS2 Topic Hierarchy, enabling data consumers to easily find topics relevant to their needs.
* Data consumers should subscribe to notifications from a Global Broker, not directly from the Message Brokers operated by WIS2 Nodes.

==== 2.4.3 Global Cache
* WIS2 incorporates several Global Caches, ensuring the highly resilient distribution of data across the globe.
* A Global Cache provides a highly available data server, from which a data consumer can download core data, as specified in Resolution 1 (Cg-Ext(2021)).
* A Global Cache subscribes to notification messages via a Global Broker.
* Upon receiving a notification message, the Global Cache downloads a copy of the data referenced in the message from the WIS2 Node, makes these data available on its server, and publishes a new notification message informing data consumers that they can now access these data on its server. 
* A Global Cache will subscribe to notification messages from other Global Caches, enabling it to download and republish data that it has not acquired directly from WIS2 Nodes. This ensures that each Global Cache holds data from every WIS2 Node.
* A Global Cache shall retain a copy of the core data for a duration compatible with the real-time or near-real-time schedule of the data and not less than 24 hours.
* A Global Cache will delete data from the cache once the retention period has expired.
* Data consumers should download data from a Global Cache when those data are available.

==== 2.4.4 Global Discovery Catalogue
* WIS2 includes several Global Discovery Catalogues.
* A Global Discovery Catalogue enables a data consumer to search and browse descriptions of data published by each WIS2 Node. The data description (discovery metadata) provides sufficient information to determine the usefulness of the data and how it may be accessed.
* A Global Discovery Catalogue subscribes to notification messages about the availability of new (or updated) discovery metadata via a Global Broker. It downloads a copy of the discovery metadata and updates the catalogue.
* A Global Discovery Catalogue amends discovery metadata records to add details of where one can subscribe to updates about the dataset at a Global Broker.
* A Global Discovery Catalogue makes its content available for indexing by search engines.

==== 2.4.5 Global Replay
* WIS2 may include a Global Replay.
* The Global Replay provides the Global Cache, Global Discovery Catalogue and data consumers with a mechanism to search, query and subscribe to past notification messages and monitoring events of interest as published by the Global Broker.
* A Global Replay subscribes to all notification messages and monitoring events as published by Global Broker. It stores the notification message and monitoring events.
* A Global Replay shall store copies of notification messages and monitoring events for a duration compatible with the real-time or near real-time schedule of the data and not less than:
** 3 days for notification messages.
** 7 days for monitoring events.
* A Global Replay will disard notification messages and monitoring events once the retention period has expired.

==== 2.4.6 Global Monitor
* WIS2 includes a Global Monitor service.
* The Global Monitor collects metrics from WIS2 components.
* The Global Monitor provides a dashboard that supports the operational management of the WIS2 system.
* The Global Monitor tracks:
  i) What data is published by WIS2 Nodes;
  ii) Whether the data can be effectively accessed by data consumers;
  iii) The performance of components in the WIS2 system.

=== 2.5 Protocol configuration

==== 2.5.1 Publish-subscribe protocol (MQTT)

* The MQTT protocolfootnote:[See MQTT Specifications: https://mqtt.org/mqtt-specification/.] is to be used for all WIS2 publish-subscribe workflows (publication and subscription).
* MQTT v3.1.1 and v5.0 are the chosen protocols for the publication of and subscription to WIS2 notification messages.
** MQTT v5.0 is preferred for connecting to Global Brokers as it provides additional features such as the ability to use shared subscriptions.
* The following parameters are to be used for all MQTT client/server connections and subscriptions:
** Message retention: false;
** Quality of Service (QoS) of 1;
** A maximum of 2000 messages to be held in a queue per client.
* To enable user authentication and authorization, WIS2 Nodes, Global Caches, Global Discovery Catalogues and Global Brokers shall use a user and password based mechanism.
* To improve the overall level of security of WIS2, the secure version of the MQTT protocol is preferred. If used, the certificate must be valid.
* The standard Transmission Control Protocol (TCP) ports to be used are 8883 for Secure MQTT (MQTTS) and 443 for Secure Web Socket (WSS).

==== 2.5.2 Download protocol (HTTP)

* The HTTP protocol (RFC 7231footnote:[See RFC 7231 - Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content: https://datatracker.ietf.org/doc/html/rfc7231.]) is to be used for all WIS2 download workflows.
* To improve the overall level of security of WIS2, the secure version of the HTTP protocol is preferred. If used, the certificate must be valid.
* The standard TCP port to be used is 443 for Secure HTTP (HTTPS).
