[appendix]
:appendix-caption: Annex

== Recommended practices for audit and certification of WIS Centres

=== Background

The Infrastructure Commission is responsible for certification of WIS centres’ compliance with the WIS technical specifications defined in the Manual on WIS. The INFCOM will maintain, within the structure of its SC-IMT on Information Management and Technology (SC-IMT), and the Expert Team on Audit and Certification (ET-AC) to coordinate audits and certification of WIS centres.

Audits and certifications will be carried out in line with the principles established in the Technical Regulations (WMO-No. 49), Volume I: General Meteorological Standards and Recommended Practices, Part VII.

=== Auditing and certification

Auditors and certifiers shall be or shall become members of ET-AC. New members must have relevant technical or auditing experience. They must be members (core or associate) of an SC-IMT expert team or have written commitment of the Permanent Representative of their country with WMO allowing them to participate as members of the ET-AC. New members will be mentored by a nominated existing expert. Note that regional diversity of members of ET-AC is essential. Access to ET-AC Workspace and online databases is restricted to ET-AC and the WMO Secretariat.

==== GISC audits

The Expert Team on Audit and Certification, on behalf of INFCOM, is responsible for auditing and certification of GISCs.

A GISC should be audited by two experts, one of whom must have previous experience of auditing GISCs. Auditors should be from a different region than that of the GISC.

Travel and per diem should be at the GISC’s expense and arranged through WMO.

===== Scope of GISC audits

Full audits will cover all aspects of WIS compliance and shall include site visits using practices inline with those of the ISO 9000 series standards.

Interim audits will focus on a particular subset of topics. Actual elements to be focused on will be determined by the Standing Committee on Information Management and Technology (SC-IMT) or its delegated expert team. Centres will be told in advance on which subset of topics the interim audit will focus. Possible areas for review in interim audits include:

a) GISC operations;
b) Metadata management;
c) Monitoring;
d) Incident management
e) Quality of service provided by the GISC;
e) Coordination within its Area of Responsibility:
  i) Management of the GISC Area of Responsibility;
  ii) Capacity development;
  iii) Participation in WIS coordination and planning mechanisms 

=== DCPC certification

Data Collection or Production Centres are to be certified by the ET-AC. Where a DCPC is not using the infrastructure of its principal GISC, and its principal GISC is operational, it can be certified by ET-AC once the principal GISC has performed the necessary tests. However, if the principal GISC is not operational, the ET-CAC will arrange for a suitable GISC to perform the tests. Where a DCPC uses the infrastructure of its principal GISC, it is certified as a part of the GISC certification process.

The certification of a DCPC requires only one ET-AC coordinator, who will ask a GISC to undertake tests with the DCPC. It is expected that the centre’s principal GISC will undertake those tests.

==== Verification of compliance of NCs

Compliance of NCs is the responsibility of the Permanent Representative with WMO of the Member accountable for the centre. Verification of compliance of an NC should be done by its principal GISC. The Expert Team on Audit and Certification will monitor the NC compliance process in consultation with NCs and GISCs.

=== The review cycle

The review cycle should start from the date of INFCOM endorsement. Audits should take place within the calendar year in which the cycle ends, and their timing will need to be coordinated with the experts called upon to undertake them.

The INFCOM endorsement date should be recorded in the WIS centre database. The date on which the centre became operational should also be recorded if known. Similarly, to an ISO 9001:2015 audit process, the GISC audit will follow the principle of alternating intermediate and full audits aligned with the INFCOM/EC four-year cycle:

a) Intermediate audit (interim, four years): a mid-cycle review of performance and compliance to provide, if necessary, opportunities to introduce corrective actions well in advance of a full audit;
b) Full audit (every second audit, i.e., every eight years): this audit will result in a recommendation for confirmation or cancellation of endorsement.

==== Review of DCPCs

The DCPC review cycle will be eight years. Reviews will cover all aspects of WIS compliance.

==== Review of NCs

Review of NC compliance is the responsibility of the Permanent Representative with WMO of the Member responsible for the Centre in liaison with the NC and its principal GISC.

=== Ad hoc audits or reviews

An ad hoc audit or review can be requested by the president of INFCOM due, for example, to non-conformance causing problems with WIS operations.

=== Audit or review outcome

The outcome of the audit or review will be categorized as "endorsed", "endorsed with qualification" or "not endorsed". Audit or review recommendations will be provided to the president of INFCOM and to the Director of WIS.

=== Format of report

The Expert Team on Audit and Certification will use a template for final reports, although the content will reflect the areas audited.

=== Public notification of type of INFCOM endorsement

The endorsement of INFCOM is based on continued successful audit outcomes. Centre endorsements are published only as "INFCOM endorsed" with no public declaration of whether endorsement was with "qualifications".

Details of reviews and audits of centres are confidential. Auditors will have access to the previous reports on a centre to perform their role.

=== Review of audits with qualification

Global Information System Centres that were "endorsed with qualifications" have two years from the date of the audit to demonstrate that they have taken remedial action on the points of qualification.

The Expert Team on Audit and Certification will investigate GISCs that were "endorsed with qualifications" and have not demonstrated that they have taken remedial action within two years of the date of audit. The Expert Team should report to INFCOM on progress in addressing the aspects that incurred the "qualification" and can recommend to INFCOM that it revokes its endorsement.
