[appendix]
:appendix-caption: Annex

== Competencies

Seven competencies across four basic functional areas have been identified as follows:

. Infrastructure: manage the physical infrastructure
. Infrastructure: manage the operational applications
. Data: manage the data flow
. Data: manage data discovery
. External interactions: manage interaction among WIS centres
. External interactions: manage external user interactions
. Overall service: manage the operational service

=== Competency 1: manage the physical infrastructure

==== Competency description

Prepare, plan, design, procure, implement and operate the physical infrastructure, networks and applications required to support the WIS centre.

Many of the skills required here are generic ICT skills and will have already been acquired as part of prior education and training or will be provided by hardware and system suppliers.

==== Performance components

==== Management of information technology operations
* Maintain the system in optimal operational condition by setting and meeting service levels, including:
** Configuration;
** Preventative and corrective maintenance and servicing;
** Equipment replacement or upgrade;
** Networking and processing capacity;
** System monitoring and reporting procedures, and corrective actions;
* Provide contingency planning and operation backup and restoration;

==== Management of facilities

* Manage physical site security;
* Manage physical site environmental control.

==== Knowledge and skill requirements

* General ICT skills;
* Operation, configuration and maintenance of equipment and applications;
* Recognized information technology service management frameworks;
* Current technologies and emerging trends;
* Service level agreements.

==== Learning outcomes

Staff will be able to:

* Maintain the system in optimal operational condition;
* Plan for upgrades and operation backup and restoration;
* Maintain site security and environmental control.

Staff will learn:

* WIS specific systems;
* WIS site security policies;
* Service level agreements for the centre.

==== Learning activities

To learn how to perform the required tasks staff may:

* Attend training sessions run by providers of systems and other tools or by other training providers;
* Respond to typical monitoring reports;
* Apply WIS site security measures and respond to typical incidents;
* Apply WIS site environmental control measures and respond to typical incidents.

==== Assessment

Staff must be able to:

* Configure and maintain system components;
* Respond to monitoring reports;
* Apply WIS site security measures and respond to typical incidents;
* Apply WIS site environmental control measures and respond to typical incidents.

==== Key learning resources

* Manufacturers’ handbooks and guides;
* Documentation of centre’s facilities;
* WIS manuals and guides;
* Tools to monitor system security;
* WIS security policies;
* WIS environmental control policies.

=== Competency 2: manage the operational applications

==== Competency description

Prepare, plan, design, procure, implement and operate the applications required to support the WIS functions.

Many of the skills required here are generic ICT skills and will have already been acquired as part of prior education and training or will be provided by suppliers of applications.

==== Performance components
* Meet service levels by maintaining applications in optimal operational condition through:
* Configuration of applications;
** Monitoring and responding to applications’ behaviour;
** Preventative and corrective maintenance;
** Replacement or upgrade of applications;
* Provide contingency planning and application backup and restoration;
* Ensure data integrity and completeness in the event of system failure;
* Ensure system security.

==== Knowledge and skill requirements

* ICT skills;
* Operation, configuration and maintenance of applications;
* Recognized information technology service management frameworks;
* Current technologies and emerging trends;
* WIS functions and requirements;
* WIS security policies.

==== Learning outcomes

Staff will be able to:

* Operate, configure and maintain applications;
* Monitor applications and take corrective action;
* Apply and test WIS security protocols.

Staff will learn:

* WIS applications specific to the centre;
* WIS system security policies and procedures.

==== Learning activities

To learn how to perform the required tasks staff may:

* Attend training sessions run by providers of systems and other tools or by other training providers;
* Initiate monitoring and reporting procedures and respond to typical monitoring reports;
* Apply WIS site security measures and respond to typical incidents.

==== Assessment

Staff must be able to:

* Configure and maintain system components;
* Respond to monitoring reports;
* Apply site security measures and respond to typical incidents.

==== Key learning resources

Documentation of centre’s applications;

* Manual on the WMO Information System (WMO No. 1060), Part IV. WIS Technical Specifications (WIS TechSpec 6);
* Guide to the WMO Information System (WMO No. 1061)
* Tools to monitor system security;
* WIS security policies.

=== Competency 3: manage the data flow

==== Competency description

Manage the collection, processing and distribution of data and products through scheduled and on demand services.

==== Performance components

* Ensure collection and distribution of data and products as per data policy;
* Publish data and products;
* Subscribe to data and products;
* Encode, decode, validate and package data and products;
* Create, update and maintain data flow catalogues;
* Manage connectivity between centres;
* Control the data flow to meet service levels.

* Knowledge and skill requirements
* System and network monitoring and viewing tools;
* Data formats and protocols;
* Licensing and data policies;
* Message and file switching systems.

==== Learning outcomes

Staff will be able to:

* Transfer data and products between their centre, other WIS centres and external users;
* Request data and respond to data requests using ad hoc and routine delivery mechanisms;
* Maintain quality standards (service levels) by monitoring, and responding to, traffic flow, missing data and products, errors and service messages;
* Apply relevant data policies to data and products;
* Identify appropriate formats for data and product exchange;
* Write and read data in WIS formats using their centre’s tools.

Staff will learn:

* Data representations used in WIS and when to apply them;
* WMO data policies and how they apply to data in WIS;
* The structure of the WIS and how to use reference documents to identify and interpret the routing plans and protocols they will need to use;
* The interfaces of their centre’s WIS applications, the information they use to modify their behaviour, and the tools available to control the operation of the applications to achieve service levels;
* How to use a WIS centre interface to find and request data for delivery by ad hoc request and by subscription;
* How WIS handles backup and alternative routings to maintain continuity of data flows.

==== Learning activities

To learn how to perform the required tasks staff may:

* Subscribe to the WIS services and download data from the Global Cache;
* Using a WIS centre platform, create, modify and delete a subscription for routine delivery of a dataset;
* Use the software tools of their centre’s WIS application to exchange information between computers;
* Assess data flows by analysing monitoring reports from their applications;
* Investigate how data policy (including WMO Resolutions 1 (Cg-Ext 2021) is applied to data published by their centre;
* Use tools provided at their centre to view information in different formats and convert data between these formats.

==== Assessment

Staff must be able to:

* Go to a WIS centre, find data, download them immediately, subscribe for regular delivery and cancel the subscription;

==== Key learning resources

Data policies

* Resolution 1 (Cg-Ext 2021) – WMO Unified Data policy for the exchange of WMO Unified Data Policy for the exchange of earth system data (weather, climate, hydrology, ocean, atmospheric composition, cryosphere, space weather) including guidelines on the relationships in commercial meteorological activities;
The centre’s data policies.

Data representations

* Manual on Codes (WMO No. 306), Volume I.1; Volume I.2 and Volume I.3;
* Guidance on migration to table driven code forms available at http://www.wmo.int/pages/prog/www/WMOCodes.html;
* Tools used at the centre to read, write, convert, validate and display information in Table Driven Code Forms;
* Sample data for reading and writing in Table Driven Code Forms.

WIS discovery, access and retrieval

* Manual on the WMO Information System (WMO No. 1060), Part IV. WIS Technical Specifications (WIS TechSpec 2, 3, 4, and 5);
* Guide to the WMO Information System (WMO No. 1061);
* User account at a GISC accessible via a Web browser.

Managing data exchange

* Manual on the WMO Information System;
* Weather Reporting (WMO No. 9), Volume C1Volume C1;
* Training environment on message and file switch;
* World Weather Watch quantity monitoring statistics
* WIGOS Data Quality Monitoring.

Security of data exchange

* Guide to Information Technology Security (WMO No. 1115).

Network management

* Network management tool and associated documentation;
* System error reports and event viewing tools.

=== Competency 4: manage data discovery

==== Competency description

Create and maintain discovery metadata records describing services and information, and upload them to the WIS Discovery Metadata Catalogue.

Each datum and product record held within WIS must have metadata associated with it so that it can be found and understood. These metadata records are held in a catalogue for discovery, access and retrieval (DAR).

==== Performance components

* Create and maintain discovery metadata records describing products and services;
* Add, replace or delete metadata records within the catalogue;
* Ensure that all information and service offerings from a WIS centre have complete, valid and meaningful discovery metadata records uploaded to the catalogue.

==== Knowledge and skill requirements

* Knowledge of WMO and ISO documentation sufficient to create complete and valid metadata;
* Metadata entry and management tools;
* Policies;
* Discovery metadata concepts and formats;
* Written English.

==== Learning outcomes

Staff will be able to:

* Use standard WIS tools to create discovery metadata from descriptions supplied by users;
* Add, replace or delete metadata records within the catalogue.

Staff will learn:

* The role of metadata in discovery, access and retrieval of data and products;
* Approved metadata formats;
* How to identify content that is mandatory, acceptable or inapplicable;
* Use of metadata creation tools;
* How to access and modify a catalogue;
* How data flow within, to and from their centre;
* About the tools that allow users to input descriptions.

==== Learning activities

To learn how to perform the required tasks staff may:

* Create metadata records based on sample descriptions for a range of data and products typical of their WIS centre;
* Insert such records into a catalogue, replace them with records that have been changed and delete them.

==== Assessment

Staff must be able to demonstrate:

* Successful creation of metadata records for typical products;
* Competence in publishing and deleting metadata catalogue records.

Key learning resources

* Manual on the WMO Information System (WMO No. 1060), Part IV WIS Technical Specifications (WIS TechSpec 1, 2, and 5), and Part V WIS Discovery Metadata;
* WCMP Homepage on WMO Community website
* WIS metadata guidance;
* Metadata entry and management tools;
* Samples of how to complete typical metadata records;
* Metadata policies and WIS metadata guidelines;
* ISO 19100 series: ISO standards on geographic information.

=== Competency 5: manage interaction among WIS Centres

==== Competency description

Manage relationships and compliance between the participants’ centre and other WIS centres.

==== Performance components

* Exchange information with other centres on operational matters;
* Facilitate registration of new WIS centres;
* Facilitate registration of new data and products by other WIS centres;
* Create and respond to WIS service messages.

==== Knowledge and skill requirements

* Knowledge of current exchanges and requirements for notification of operational changes;
* Procedures and practices for registration of other centres and their data and products;
* Service level agreements;
* Written English.

==== Learning outcomes

Staff will be able to:

* Facilitate registration of new WIS centres and their data and products;
* Keep other WIS centres informed of the status of services, incidents and requests;
* Monitor and respond to service level reports;
* Manage subscriptions.

Staff will learn:

* About current exchanges and requirements for notification of operational changes;
* What type of data, products and services are available at their centre;
* Procedures and practices for registration of other centres and their data and products;
* Procedures and practices for notifying other centres about operational changes and service availability.

==== Learning activities

To learn how to perform the required tasks staff may carry out the above activities with the help of software, tools and guidance as used in their operational environment, either in a classroom or under supervision on the job.

==== Assessment

Staff must be able to:

* Respond to a request for registration of a new centre and its data and products;
* Prepare notifications of typical operational scenarios;
* Respond to typical notifications from other WIS centres.

==== Key learning resources

* Manual on the WMO Information System (WMO No. 1060), Part III Functions of WIS, and Part IV WIS Technical Specifications;
* Guide to the WMO Information System (WMO No. 1061);
* Weather Reporting (WMO No. 9), Volume C1; 
* Exchanging Meteorological Data: Guidelines on Relationships in Commercial Meteorological Activities – WMO Policy and Practice (WMO No. 837).

==== Local resources

* Service level agreements (as used by the participants’ centre);
* Frequently Asked Questions (FAQ) documents (for the user);
* WIS software user guides;
* Guidelines for services available at WIS centre;
* Data policy and associated guidance material;
* First line support procedures and guides;
* User database (for contact information);
* Case tracking and customer management;
* WIS user management;
* WIS subscription management;
* Monitoring dashboard for WIS components.

=== Competency 6: manage external user interactions

==== Competency description

Ensure that users, including other centres, data providers and subscribers, can publish and access data and products through WIS.

==== Performance components

* Register data providers and subscribers and maintain a service agreement;
* Set and register access criteria;
* Provide systems and support for users to publish and access data and products;
* Manage user relations to ensure a high satisfaction level.

==== Knowledge and skill requirements

* Data policies;
* External WIS interface;
* WIS registration and monitoring tools and policies;
* User support documentation and help files;
* Written English.

==== Learning outcomes

Staff will be able to:

* Register new WIS users and providers, setting roles, access authorizations and levels;
* Create and amend WIS user subscriptions;
* Use WIS tools to assist users and providers in resolving problems;
* Create and respond to WIS service messages;
* Undertake first line investigation and diagnosis;
* Manage incidents and requests: log them, categorize and prioritize them, escalate as appropriate and close them when the user is satisfied;
* Keep users informed of the status of services, incidents and requests;
* Gather information and report on user and provider satisfaction;
* Assist users in uploading and accessing data;
* Identify potential problems in services and implement improvements.

Staff will learn:

* What type of data, products and services are available at their centre;
* How WIS applications, including discovery, access and retrieval (DAR) should be used;
* How to apply data policies;
* How to interact effectively with users and providers.

==== Learning activities

To learn how to perform the required tasks staff may:

* Register users (data providers and subscribers) and set access authorizations and levels using the same software, tools and guidance as in their operational environment;
* Role play user interactions.

==== Assessment

Staff must be able to:

* Register typical data providers and users;
* Ensure that users are able to upload and access data;
* Respond to typical incidents.

==== Key learning resources

* Manual on the WMO Information System (WMO No. 1060), Part IV WIS Technical Specifications (WIS Tech Spec 2, 3, 4, and 5);
* Guide to the WMO Information System (WMO No. 1061);
* Weather Reporting (WMO No. 9), Volume C1;
* Exchanging Meteorological Data: Guidelines on Relationships in Commercial Meteorological Activities – WMO Policy and Practice (WMO No. 837).

Local resources

* level agreements (as used by their centre);
* FAQ documents (for the user);
* WIS software user guides;
* Guidelines for services available at WIS centre;
* Data policy and associated guidance material;
* First line support procedures and guides;
* User database (for contact information);
* Case tracking and customer management;
* WIS user management;
* WIS subscription management;
* Monitoring dashboard for WIS components.

=== Competency 7: manage the operational service

==== Competency description

Ensure the quality and continuity of the service.

This is essentially a management role ensuring that the WIS system operates as required, now and in the future. Some of the skills required are generic management skills, rather than WIS specific, and would be taught or learnt elsewhere.

==== Performance components
* Coordinate all WIS functions and activities of the centre;
* Ensure and demonstrate compliance with regulations and policies;
* Monitor and meet quality and service performance standards;
* Ensure service continuity through risk management and planning and implementation of service contingency, backup and restoration. Ensure data continuity in the event of system failure;
* Plan and coordinate the delivery of new functionalities.

==== Knowledge and skill requirements

* General management skills;
* Overview of local and external WIS operations and associated service agreements;
* WIS regulations and policies;
* Functional specifications;
* Written English.

==== Learning outcomes

Staff will be able to:

* Ensure that the WIS centre meets quality and service performance standards;
* Identify the challenges and issues to be addressed;
* Foster compliance with WIS framework.

Staff will learn:

* Functions and responsibilities of the WIS centre;
* WIS quality and service performance standards;
* Methods to manage quality, risk and operational service;
* How to monitor quality and service performance standards;
* How to analyse, demonstrate and report quality and service performance at the WIS centre;
* How to maintain troubleshooting, backup and restoration procedures;
* How to plan and coordinate the delivery of new functionalities and improvements;
* How to integrate new technologies and developments;
* How to update the regulatory documents;
* How to maintain service agreements;
* How to plan monitoring resources;
* How to align budget restrictions with human resources demands.

==== Learning activities

To learn how to perform the required tasks staff may:

quality and service performance standards;
Analyse quality and service performance in the WIS centre;
Demonstrate and report quality and service performance;
Maintain troubleshooting, backup and restoration procedures;
Plan and coordinate the delivery of new functionalities;
Keep timely records, as required.

==== Assessment

Staff must be able to:

* Demonstrate successful WIS service;
* Plan replacement and upgrade of equipment and applications to meet new functionalities and requirements.

==== Key learning resources

* Technical Regulations (WMO No. 49), Volume I;
* Resolution 1 (Cg-Ext 2021) – WMO Unified Data Policy for the exchange of earth system data (weather, climate, hydrology, ocean, atmospheric composition, cryosphere, space weather) including guidelines on the relationships in commercial meteorological activities;
* Manual on the WMO Information System (WMO No. 1060), Part IV WIS Technical Specifications (WIS TechSpec 6);
* Guide to the WMO Information System (WMO No. 1061);
* WIS demonstration procedures and guidelines;
* Monitoring reports;
* Audit reports.
