== Implementation and operation of a Global Service

=== Procedure for registration of a new Global Service

During the initial stages of the WIS2 pilot phase an informal process is used to register interest in operating a Global Service. Candidate WIS Centres should inform their WIS Focal Point and contact the WMO Secretariat to discuss their offer to provide a Global Service.

=== Performance management and monitoring of a Global Service

==== Service levels, performance indicators, and fair-usage policies

TODO: to be completed

==== Provision of metrics

TODO: to be completed

=== Global Broker

==== Technical considerations

* There will be multiple Global Broker instances to ensure highly available, low latency global provision of messages within WIS.
* A Global Broker instance subscribes to messages from NC/DCPCs and other Global Brokers
* A Global Broker instance will subscribe to messages from a subset of NC/DCPCs and republish them.
** A Global Broker obtains the following list of metadata fields for each of the WIS nodes in the subset of NC/DCPCs covered by this Global Broker, from the Global Registry: Hostname and port(s) of broker, center_id, list of supported protocols (MQTT, MQTTs, web-socket). 
** A Global Broker uses the username/password combination "everyone/everyone" to subscribe to the topic corresponding to the WIS node using one of the supported protocols.
* At least one Global Broker will subscribe to messages from every NC/DCPC.
* For full global coverage, a Global Broker instance will subscribe to messages from other Global Broker instances and republish them.
* A Global Broker instance will republish a message only once – noting that a particular message may be received multiple times (e.g., from different sources). Discarding duplicate messages is referred to as "anti-loop".
* It is not required that a Global Broker instance republishes messages from all other Global Brokers (e.g., establishing ‘fully meshed’ connection). However, it is essential that messages propagate through WIS efficiently and effectively, from originating NC/DCPC to Data Consumers in all Regions. Consequently, it is recommended that topological distance between every Global Broker shall not exceed 3 "hops"  (i.e., a message received at a Global Broker shall be republished by no more than 3 other Global Brokers on its route from the originating NC/DCPC). Connectivity between Global Brokers will be recommended by Experts from INFCOM/SC-IMT. 
* Global Brokers use distinct "channels" to keep messages from originating NC/DCPC separate from messages originating from Global Cache instances. This is implemented in using the top-level ("channel") of the topic structure (see WIS2 messages
* 4.4 	Standard topic hierarchy). 
* A Global Broker will validate notification messages against the standard format (see 4.3 	Notification message format and structure), discarding non-compliant messages and raising an alert.
* A Global Broker is built around two software components:
** An off the shelf broker implementing both MQTT 3.1.1 and MQTT 5.0 in a highly-available setup (cluster)Tools such as EMQX, HiveMQ, VerneMQ are compliant with these requirements.
** Additional features (anti-loop, message format compliance,…) are required. An open source implementation will be made available during the pilot phase.
* A Global Broker maintains the list of IP addresses used for outgoing subscription connections to WIS nodes in the Global Registry. The Global Broker must announce changes to these IP addresses at least one month before implementing these changes.

TODO: to be completed

==== Practices and procedures

The following procedures will be described here once validated through testing during the WIS2 pilot phase:

* Assigning a Global Broker to a NC or DCPC
* Alerting originating NC or DCPC about malformed or non-compliant messages

TODO: to be completed

=== Global Cache

==== Technical considerations

* The Global Cache will contain copies of real-time and near real-time data designated as "core" within the WMO Unified Data Policy (Resolution 1).
* During the initial stages of the WIS2 pilot phase Global Cache instances will provide open access to their cached content. Access control mechanisms may be added later.
* A Global Cache instance will host data objects copied from NC/DCPCs. These are persisted as files.
* A Global Cache instance will publish notification messages advertising availability of the data objects it holds. The notification messages will follow the standard structure (see 4.3 	Notification message format and structure).
* A Global Cache instance will use the standard topic structure in their local message brokers (see WIS2 messages 4.4 Standard topic hierarchy).
* There will be multiple Global Cache instances to ensure highly available, low latency global provision of real-time and near real-time "core" data within WIS.
* Global Cache instances may attempt to download cacheable data objects from all originating centres with "cacheable" content. A Global Cache instance will also download data objects from other instances. This ensures the instance has full global coverage, mitigating where direct download from an originating centre is not possible.
* For full global coverage, a Global Cache instance will download Data Objects and discovery metadata records from other instances.
* Global Cache instance will operate independently of other Global Cache instances. Each Global Cache instance will hold a full copy of the cache – albeit that there may be small differences between Global Cache instances as "data availability" notification messages propagate through WIS to each Global Cache in turn. There is no formal ‘synchronisation’ between Global Cache instances.
* A Global Cache will store a full set of discovery metadata records. This is not an additional metadata catalogue that Data Consumers can search and browse – it provides a complete set of discovery metadata records to support populating a Global Discovery Catalogue instance.
* A Global Cache is designed to support real-time distribution of content. Data Consumers access data objects from a Global Cache instance by resolving the URL in a "data availability" notification message and downloading the file. 
* There is no requirement for a Global Cache to provide a "browse-able" interface to the files in its repository allowing Data Consumers to discover what content is available. However, a Global Cache may choose to provide such a capability (e.g., implemented as a "Web Accessible Folder", or WAF) along with adequate documentation for Data Consumers to understand how the capability works.
* A Global Cache maintains the list of IP addresses used for outgoing connections to WIS nodes in the Global Registry. The Global Cache must announce changes to these IP addresses at least one month before implementing these changes.

TODO: to be completed

==== Practices and procedures

The following procedures will be described here once validated through testing during the WIS2 pilot phase:
* Assigning a Global Cache to a NC or DCPC
* Lifecycle management of discovery metadata records stored in the Global Cache.

TODO: to be completed

=== Global Discovery Catalogue

==== Technical considerations

* The Global Discovery Catalogue provides Data Consumers with a mechanism to discover the Datasets of interest, as well as, how to interact with and find out more information about those Datasets.
* The Global Discovery Catalogue implements the OGC API – Records – Part 1: Core standard.
* The Global Discovery Catalogue advertises the availability of Datasets and how/where to access them or subscribe to updates, it does not advertise the availability of individual Data Objects that comprise a dataset (i.e., data files).
* A single Global Discovery Catalogue instance is sufficient for WIS2.
* Multiple Global Discovery Catalogue instances may be deployed for resilience.
* Global Discovery Catalogue instances operate independently of each other – each Global Discovery Catalogue instance will hold all discovery metadata records. There is no need to synchronise between Global Discovery Catalogue instances.
* A Global Discovery Catalogue is populated with discovery metadata records from a Global Cache instance – receiving messages about availability of discovery metadata records via a Global Broker.
* A Global Discovery Catalogue should connect to more than one Global Broker instance to ensure that no messages are lost in the event of a Global Broker failure. A Global Discovery Catalogue instance shall discard duplicate messages as needed.
* A Global Discovery Catalogue will validate discovery metadata records against the WMO Core Metadata Profile version 2 (WCMP2), discarding non-compliant records and raising an alert.
* A Global Discovery Catalogue will update discovery metadata records it receives to add links for subscription URLs at Global Broker instances.
* A Global Discovery Catalogue should applying faceting capability as specified in the cataloguing considerations of the WCMP2 specification as defined in OGC API - Records.
* A Global Discovery Catalogue shall provide human-readable Web pages with embedded markup using the schema.org vocabulary, thereby enabling search engines to crawl and index the content of the Global Discovery Catalogue. Consequently, Data Consumers should also be able to discover WIS content via third party search engines.
* A Global Discovery Catalogue shall periodically assess the discovery metadata provided by NCs and DCPCs against a set of key performance indicators (KPIs) in support of continuous improvement. Suggestions for improvement are shared with the originating NC or DCPC and their primary GISC.

TODO: to be completed

==== Practices and procedures

The following procedures will be described here once validated through testing during the WIS2 pilot phase:

* Alerting originating NC or DCPC about malformed or non-compliant discovery metadata records
* Providing feedback to NC and DCPC about how to improve their discovery metadata
* Removing discovery metadata for a Dataset on request
* ‘Bootstrapping’ a Global Discovery Catalogue instance from the Global Cache

TODO: to be completed

=== Global Monitor

==== Technical Considerations
* WIS2 standardises how system performance and data availability metrics are published from WIS nodes and Global Services.
* The Global Monitor will collect metrics as defined in the OpenMetrics standard.
* The Global Monitor will monitor the 'health' (i.e., performance) of components at NC/DCPC as well as Global Service instances.
* The Global Monitor will provide a Web-based ‘dashboard’ that displays the WIS2 system performance and data availability.

TODO: to be completed

==== Practices and procedures 

Procedures pertinent to the Global Monitor will be described here once validated through testing during the WIS2 pilot phase.

TODO: to be completed

=== Global Registry ===

* The role of the Global Registry is to make available the information required for Global Services and WIS nodes to connect with each other. 
* The Global Registry makes available to Global Brokers the list of registered WIS Nodes. The following metadata is made available for each WIS Node: hostname and port(s) of local broker, center_id, list of implemented protocols (MQTT, MQTTs, web-socket).
* The Global Registry makes available to WIS nodes the list of IP addresses used by Global Brokers and Global Caches to subscribe to and download data from WIS nodes.
* The Global Registry provides authorized contacts the means to update information about their WIS Node or Global Services.
* The Global Registry makes information available in such a way that minimizes the downtime of WIS nodes in case of changes to a node's metadata.

==== Service level

* The Global Registry is a non-operational service. Nodes obtaining information from the Global Registry shall make provisions to keep operating without the Global Registry for at least 14 days.
