== Introduction
=== Purpose

In conjunction with the https://library.wmo.int/idurl/4/68731[_Manual on the WMO Information System_] (WMO-No. 1060), Volume II – WMO Information System 2.0 (_Manual on WIS_, Volume II), the present _Guide to the WMO Information System_ (WMO-No. 1061), Volume II – WMO Information System 2.0 _(Guide to WIS_, Volume II) is designed to ensure adequate uniformity and standardization in the data, information and communication practices, procedures and specifications employed by WMO Members in the operation of the WMO Information System WIS 2.0 as it supports the mission of the Organization. The _Manual on WIS_, Volume II contains standard and recommended practices, procedures and specifications. The _Guide to WIS_, Volume II contains additional information concerning practices, procedures and specifications that Members are invited to follow or implement in establishing and conducting their arrangements in compliance with the WMO technical regulations and in developing meteorological and hydrological services.