:sectnums!:
== Introduction
=== Purpose

In conjunction with the https://library.wmo.int/idurl/4/68731[Manual on the WMO Information System] (WMO-No. 1060), Volume II – WMO Information System 2.0 (Manual on WIS, Volume II), the present Guide to the WMO Information System, Volume II – WMO Information System 2.0 (Guide to WIS, Volume II) is designed to ensure adequate uniformity and standardization in the data, information and communication practices, procedures and specifications employed by Members of the World Meteorological Organization (WMO) in the operation of the WMO Information System WIS 2.0 as it supports the mission of the Organization. The Manual on WIS, Volume II contains standard and recommended practices, procedures and specifications. The Guide to WIS contains additional information concerning practices, procedures and specifications that Members are invited to follow or implement in establishing and conducting their arrangements in compliance with the WMO technical regulations and in developing meteorological and hydrological services.

:sectnums:
