== Introduction of WIS2

Since the Global Telecommunication System (GTS) entered operational life in 1971, it has been a reliable real-time exchange mechanism of essential data for WMO members. 

In 2007, the WMO Information System (WIS) entered into operations to complement the GTS, providing a searchable catalogue and a global cache to enable additional discovery, access and retrieval. The success of WIS was limited as the system only partially met the requirement of providing simple access to WMO data. Today's technology developed for the Internet of Things (IoT) opens the possibility of creating a WIS 2.0 able to stand to its expectations of delivering an increasing number and volume of real-time data to WMO Centres in a reliable and cost effective way.

WIS 2.0 has been designed to meet the shortfalls of the current WIS and GTS, support the WMO’s Unified Data Policy and the Global Basic Observing Network (GBON), and meet the demand for high data volume, variety, velocity and veracity. 

WIS 2.0 technical framework is based around three foundational pillars: leveraging open standards, simpler data exchange and cloud-ready solutions.

=== Leveraging open standards

WIS 2.0 leverages open standards to take advantage of the ecosystem of technologies available on the market and avoid building bespoke solutions that can force NMHSs to procure costly systems and equipment. In today's standards development ecosystem, standards bodies work closely together to minimise overlap and build on one another's areas of expertise. For example, the World Wide Web Consortium provides the framework of Web standards, which the Open Geospatial Consortium and other standards bodies leverage. WIS 2.0 leverages open standards with industry adoption and wider, stable, and robust implementations, thus extending the reach of WMO data sharing and lowering the barrier to access by Members.

=== Simpler data exchange

WIS 2.0 prioritises public telecommunication networks, unlike private networks for GTS links. As a result, using the Internet will enable the best choice for a local connection, using commonly available and well-understood technology. 

WIS 2.0 aims to improve the discovery, access and utilisation of weather, climate and water data by adopting Web technologies proven to provide a truly collaborative platform for a more participatory approach. Data exchange using the Web also facilitates easy access mechanisms. Browsers and search engines allow Web users to discover data without specialised software. The Web also enables additional data access platforms, e.g. desktop GIS, mobile applications, forecaster workstations, etc.
The Web provides access control and security mechanisms that can be utilised to freely share the core data per the WMO Unified Data Policy and protect the data with more restrictive licensing constraints. Web technologies also allow for authentication and authorisation for the provider to retain control of who can access published resources and to request users to accept a license specifying the terms and conditions for using the data as a condition for providing access to them.

WIS 2.0 uses a "publish-subscribe" pattern where users subscribe to a topic to receive new data in real time. The mechanism is similar to WhatsApp and other messaging applications. It is a reliable and straightforward way to allow the user to choose her data of interest and to receive them reliably. 

=== Cloud-ready solutions

The cloud provides reliable platforms for data sharing and processing. It reduces the need for expensive local IT infrastructure, which constitutes a barrier to developing effective and reliable data processing workflows for some WMO Members. 
WIS 2.0 encourages WMO centres to adopt cloud technologies where appropriate to meet their users' needs. Whilst WMO technical regulations will not mandate cloud services, WIS 2.0 will promote a gradual adoption of cloud technologies that provide the most effective solution. 

The cloud-based infrastructure allows easy portability of technical solutions, ensuring that a system implemented by a specific country can be packaged and deployed easily in other countries with similar needs. In addition, using cloud technologies allows WIS 2.0 to deploy infrastructure and systems efficiently with minimum effort for the NMHSs by shipping ready-made services and implementing consistent data processing and exchange techniques.

It should be clear that hosting data and services on the cloud does not affect data ownership. Even in a cloud environment, organisations retain ownership of their data, software, configuration, and change management as if they were hosting their infrastructure. As a result, data authority and provenance stay with the organisation, and the cloud is simply a technical means to publish the data. 

=== Why are datasets so important?

The purpose of WIS is to enable sharing of data. "Datasets" provide the mechanism for us to describe what data we publish, or what data we’re interested in.

Data comes in all shapes and sizes. Often, our data is continually updated (e.g., new observations from an automatic weather station). Sometimes it is very, very big (e.g., a set of climate predictions or a multi-decadal reanalysis). WIS2 aims to make it simple to talk about collections of data that share similar characteristics.

We call these collections of data "Datasets".

A Dataset may comprise of thousands of individual files – like scene from an imaging satellite, or fields from a numerical weather prediction model. Or it may comprise huge numbers of records in a database – like a time-series of physical property values observed at numerous locations. 

However, the data is stored, we describe the collection of files, records, whatever (!) as a Dataset. But there are some rules. The data in a Dataset must be consistent – it must have the same type (e.g., time-series at point locations), subject (e.g., observations of physical properties), and any spatiotemporal referencing so that people can structure sensible queries on the Dataset. A Dataset must also have a single usage or access policy, which implies a Dataset will be subject to a single governance regime and will likely have a single owner. Most importantly, the contents of a Dataset must be available from a single access point so that we can tell Data Consumers where they can download data from. We also need to use a single topic for publishing notifications about the availability of new data within a Dataset.

It is up to Data Publishers to decide how they group data into Datasets. That said, we recommend that, subject to the consistency rules, Data Publishers should organise their data into as few Datasets as possible. For a Data Publisher this means fewer discovery metadata records to maintain. For a Data Consumer this means fewer topics to subscribe to, and lower barrier APIs and Web services to access.

A real-world example for an NMHS to package all synoptic observations for the entire country or territory into a single Dataset footnote:[Probably keep archived synoptic observations separate from those being collected in (near) real-time because they’re likely accessed through different Web-services.] footnote:[This is contrary to earlier practices in WIS where each GTS bulletin was considered a Dataset. This meant that the WIS Catalogue became overburdened with hundreds of thousands of records, each describing more-or-less the same thing. The result was a very poor search experience – always too many ‘hits’!]. Described with a single discovery metadata record. Accessible via a single Web-service.

Finally, note that the notification messages used to advertise the availability of new data themselves contain metadata (time, location, etc.). This allows for Data Consumers to decide whether or not they want to download a specific file or record.
