== Quickstarts

This section lists the sections in this technical guidance document that are essential for Data Publishers operating a WIS2 Node (e.g., an NC or a DCPC) and Data Consumers to read before getting started.
Operators of GlSCs should have an in-depth understanding of how WIS2 functions and operates – not least so that they are able to effectively support the WIS Centres, Data Publishers, and Data Consumers in their Area of Responsibility (AoR). As such, all contents of this guidance document are relevant to GISCs.

=== Data publisher

As a Data Publisher planning to operate a WIS2 Node, you should read the following sections: TODO: fix crossrefs
* 1.2: What is WIS2?
* 1.3 Why are Datasets so important?
* PART III Data Metadata flows
* PART X Information Management

==== How to publish Dataset discovery metadata to the Global Discovery Catalogue

A Data Producer publishes discovery metadata to the Global Discovery Catalogue by generating a discovery metadata record (see PART V Discovery Metadata) and publishing it via a WIS2 Node broker in accordance to the WIS2 Topic Hierarchy. Global Services subscribed to WIS2 Nodes then validate, ingest and publish the Dataset discovery metadata record to the Global Discovery Catalogue.

==== How to publish data notifications

A Data Producer publishes data notifications by generating a notification message (see 7.2.2 Notification_messages) via a WIS2 Node broker in accordance with the WIS2 Topic Hierarchy. Global Brokers subscribe to WIS2Nodes and then re-publish the data notification. If applicable, Global Cache ingests the associated file or data for re-publication to the Global Broker.

==== How to publish data to the Global Broker

Data publishing is realized as a function of publishing data notifications (see 2.1.2 How to publish data notifications ).

TODO: To be completed

=== Data consumer

As a Data Consumer wanting to use data published via WIS2 you should read the guidance presented here. In addition, a list of references to useful sections in this guidance document is provided where Data Consumers can gain a better understanding of how WIS2 works.

==== How to search the Global Discovery Catalogue to find Datasets

A Data Consumer may browse discovery metadata provided by the Global Discovery Catalogue to locate a Dataset of interest. Discovery metadata follows a standard scheme (see PART V Discovery Metadata). A Data Consumer may discover a Dataset using keywords, topics, geographic area of interest, or date(s) associated with the Dataset. Matching search results from the Global Discovery Catalogue provide high-level information (title, description, keywords, spatiotemporal extents, data policy, licensing), from which a Data Consumer can assess and evaluate their interest in accessing/downloading the Dataset’s data.

A key component of Dataset records in the Global Discovery Catalogue is that of "actionable" links.  A Dataset record provides one to many links that clearly identify the nature of the link (informational, direct download, API) so that the Data Consumer can interact with the data accordingly. For example, a Dataset record may include a link to subscribe to notifications (see 2.2.2 how to subscribe to notification about availability of new data) about the data, or a API, or an offline archive retrieval service.

TODO: To be completed

==== How to subscribe to notifications about availability of new data

A Data Consumer may browse the topics provided by a Global Broker to locate a Dataset of interest to them.  Topic structures follow the WIS2 Topic Hierarchy. A Data Consumer may discover more about the Dataset associated with a particular topic by using the topic-name as a key to search the Global Discovery Catalogue.

Data Consumers should subscribe to receive "data availability" messages from Global Brokers. Exceptionally, a Data Consumer may choose to subscribe directly to the local message broker at the originating NC/DCPC – but note that the NC/DCPC may not provide public access to its local message broker. Data Consumers should not subscribe to the local message broker at Global Cache instances.

Real-time and near real-time data designated as "Core" in the WMO Unified Data Policy (Resolution 1) will be available from the Global Cache. As per clause 3.2.13 from the Manual on WIS, Vol II. Data Consumers should access data from the Global Cache.

When a Dataset is available from the Global Cache, its discovery metadata will include a link to subscribe to "data availability" messages from the Global Cache instances. Data Consumers will subscribe to these "Global Cache" topics and not to the topic that contains messages from the originating NC/DCPC.

TODO: To be completed

==== How to use a notification message to decide whether to download data

Each Global Cache will publish a "data availability" message as the associated data object becomes available from that Global Cache instance. Each "data availability" message will refer to the same logical data object but hosted at a different location within WIS. Data Consumers need to consider their strategy for managing these duplicate messages. From a data perspective, it does not matter which Global Cache instance is used – they will all provide an identical copy of the data object published by the originating NC/DCPC. The simplest strategy is to accept the first "data availability" message and download from the Global Cache instance that the message refers to (i.e., using a URL for the data object at that Global Cache instance). Alternatively, a Data Consumer may have a preferred Global Cache instance, for example, that is located in the Region. Whichever Global Cache instance is chosen, Data Consumers will need to implement logic to discard duplicate "data availability" messages.

TODO: To be completed

==== How to download data from the Global Cache and WIS2 Nodes

Dataset links are made available through Dataset discovery metadata (via the Global Discovery Catalogue) as well as data notification messages (via Global Brokers). Links can be used to download the data (according to the network protocol and content description provided in the link) using a mechanism appropriate to the workflow of the Data Consumer. This could include web and/or desktop applications, custom tooling, or other approaches.

TODO: To be completed

==== Additional sections of interest to a Data Consumer (TODO: fix crossref)

* 1.2	 What is WIS2?
* 1.3 	Why are Datasets so important?
[To be completed]
