=== 3.3 Sensor Centres

Sensor Centres are components external to WIS 2.0, which provide continuous assessments on functionality.  Sensor
Centres can provide external feedback on WIS 2.0 functions to trigger corrective action in support of continuous improvement.

==== 3.3.1 Overview

As described in the Manual on WIS, Volume II, WIS 2.0 is a collective, distributed data exchange system that requires monitoring. 

All WIS 2.0 components have defined metrics and conditions on those metrics to trigger alerts.

The Global Monitor collects the metrics and presents them a suite of dashboards enabling observability, visuaization and analysis.

Beyond WIS 2.0 itself, a Sensor Centre relies on WIS 2.0 Global Services and Nodes. It implements further processing on any component of the WIS 2.0 architecture.  This procesing results in additional metrics which can also be provided to dashboards, within or external to WIS 2.0.

==== 3.3.2 Sensor Centres for Global Brokers (SCGB)

===== 3.3.2.1 Technical considerations

* As a convention, the Sensor Centre for Global Broker centre-id will be ``{tld}-{centre-name}-sensor-centre-global-broker``.

==== 3.3.3 Sensor Centres for Global Caches (SCGC)

===== 3.3.3.1 Technical considerations

* As a convention, the Sensor Centre for Global Cache centre-id will be ``{tld}-{centre-name}-sensor-centre-global-cache``.

==== 3.3.4 Sensor Centres for Global Discovery Catalogues (SCGDC)

The primary function of an SCGDC is to test and evaluate content parity across all GDCs in WIS 2.0.

A Global Discovery Catalogue (GDC) must publish, every 24 hours, a zip file containing all metadata records available via the GDC API.

A GDC Sensor Centre checks all GDCs are publishing the zip file and then analyzes the content of the zip file (all metadata records) to detect anomalies (i.e. missing metadata records, inconsistent data records between GDCs, validating metdata records for WCMP2 compliance).

Metadata content must be identical for all GDCs. The SCGDC verifies this consistency provides the necessary insights to trigger corrective action of the discrepancies.

===== 3.3.4.1 Technical considerations

* The SCGDC will connect to a minimum of two Global Brokers. 
* The SCGDC subscribes to the metadata topic for all GDCs, by one of the following methods:
** subscribing to ``cache/a/wis2/+/metadata/#``, discarding all Notification Messages whose centre identifier (in the topic) does not end with ``-global-discovery-catalogue``.
** subscribing to each GDC via ``cache/a/wis2/centre-id/metadata/#``.
* The SCGDC will use the link provided in the WIS2 Notification Message received to download the zip file published by the GDC.
* For each GDC centre identifier, upon successful download of the zip file, the SCGDC will update the metric ``wmo_wis2_scgdc_last_download_timestamp_seconds`` with the timestamp (in seconds) of the last successful download.
* Once a day, the SCGDC will analyze the content of the latest zip files received across all GDCs
** Files older than 24 hours will not be analyzed.
* The SCGDC will set the metric ``wmo_wis2_scgdc_records_incorrect_total`` to ``0`` at the beginning of the analysis for all GDCs where the zip file is less than 24 hours old. *Note*: the metric ``wmo_wis2_scgdc_records_incorrect_total`` is a gauge (not a counter) whose value can be reset to ``0`` at the beginning of the analysis.
* After unpacking the zip file, the SCGDC will update the metric ``wmo_wis2_scgdc_records_received_total`` with the number of records found in the zip file.
* For each record, the SCGDC will:
** prune the `links` array. The `links` array is modified by each GDC and modifications are dependent on the GDC itself. It is therefore required to remove all links that are not `rel=license` before further processing for parity checking.
** validate the record against the latest approved version of WCMP2
*** If the record is not compliant, the SCGDC will update the metric ``wmo_wis2_scgdc_invalid_total``, with the WCMP2 id as well as centre id of the GDC
** compare each metadata record with the same WCMP2 `id` received from all other GDCs.
** If the content is the same for all GDCs, the SCGDC will increase the metric ``wmo_wis2_scgdc_records_identical_total`` by ``1``.
** If the content is different, the SCGDC will compare the record's ``properties.updated`` property, if present, across GDCs. If more than one value of ``properties.updated`` is present, the SCGDC will consider the GDC with the record of the most recent date is the canonical record.
*** In this case, the SCGDC will increase the metric ``wmo_wis2_scgdc_records_incorrect_total`` by ``1`` for all GDCs except the GDC having the most recent record.
** If the content is different, and if no GDC holds a record with ``properties.updated``, the SCGDC will consider that it is not possible to ensure which GDC has the correct record.
*** In this case, the SCGDC will increase the metric ``wmo_wis2_scgdc_records_incorrect_total`` by ``1`` for all GDCs.
* As a convention, the Sensor Centre for Global Discovery Catalogue centre-id will be ``{tld}-{centre-name}-sensor-centre-global-discovery-catalogue``.
