=== Data publisher

As a Data Publisher with authoritative Earth system data that you want to share with the WMO community you should read the guidance presented here. In addition, a list of references to informative material in this Guide and elsewhere is provided at the end of this section.

==== How to get started

The first thing you need to do is consider your data and how it can be conceptually grouped into one or more datasets (see section 1.1.4. Why are datasets so important? (TODO CROSSREF)).

If your data relates to your country or territory, you need to publish it through a National Centre (NC). If your data relates to a region, programme, or other specialized function within WMO, you need to publish it through a Data Collection or Production Centre (DCPC). The functional requirements for NC and DCPC are described in the _Manual on the WMO Information System_ (WMO-No. 1060), Vol II - Part III Functions of WIS.

All NCs and DCPCs are affiliated with a Global Information System Centre (GISC) that has a responsibility to help establish efficient and effective data sharing on the WIS.

You may be able to identify an existing NC or DCPC that can publish your data. Alternative, you need to establish a new NC or DCPC. The main difference is that an NC is designated by a Member, whereas a DCPC is designated by a WMO or related international programme and/or a regional association.

Both NC and DCPC require operation of a WIS2 Node (see section 2.4.1. WIS2 Node (TODO CROSSREF)). The procedure for registering a new WIS2 Node is provided in Section 2.6.1.1. Registration and decommissioning of a WIS2 Node (TODO CROSSREF). 

Once you have determined the scope of your datasets and have a WIS2 Node ready for data publication, you are ready to progress to the next step: providing discovery metadata.


==== How to provide discovery metadata to WIS2

Discovery metadata is the mechanism by which you tell potential consumers about your data, how it may be accessed, and any conditions you may place on the use of the data.

Each dataset you want to publish must have an associated discovery metadata record. This record is encoded as GeoJSON (RFC 7946footnote:[RFC 7946 - The GeoJSON Format https://datatracker.ietf.org/doc/html/rfc7946]) must conform to the WMO Core Metadata Profile 2 (WCMP2) specification (TODO CROSSREF).

Copies of all discovery metadata records from WIS2 are held at the Global Discovery Catalogues, where data consumers can search and browse to find data that is of interest to them. 

Depending on local arrangements, your GISC may be able to help you transfer your discovery metadata record(s) to the Global Discovery Catalogues. If this is not the case, you will need to publish the discovery metadata record(s) yourselffootnote:[In future, WIS2 may provide metadata publication services (e.g., through a WIS2 metadata management portal) to assist with this task. However, such a service is not available at this time.] (see section 2.6.2. Publishing data, discovery metadata, and notification messages (TODO CROSSREF)).

Upon receipt of a new discovery metadata record, a Global Discovery Catalogue (see section 2.4.4. Global Discovery Catalogue (TODO CROSSREF)) will validate, assess, ingest, and publish the record. Validation ensures that your discovery metadata record complies with the specification. Assessment examines your discovery metadata record against good practice (TODO CROSSREF WCMP2 KPIs). The Global Discovery Catalogue will notify you if your discovery metadata record fails validation and provide recommendations for improvements for you to consider. 

Discovery metadata must be published in the Global Discovery Catalogues before you begin publishing data.

More detail on publishing discovery metadata is provided elsewhere in this Guide (see section 2.6.2. Publishing data, discovery metadata, and notification messages (TODO CROSSREF)).

==== How to provide data to WIS2

WIS2 is based on the Web architecturefootnote:[Architecture of the World Wide Web https://www.w3.org/TR/webarch/]. As such it is _resource oriented_. Datasets are resources; the "granules" of data grouped in a dataset are resources; the discovery metadata records that describe datasets are resources. In Web architecture, every resource has a unique identifier (e.g., a URIfootnote:[RFC3986 Uniform Resource Identifier (URI) - Generic Syntax https://www.rfc-editor.org/rfc/rfc3986]), and the unique identifier can be used to resolve the resource identified and interact with it (e.g., to download a representation of the resource over an open standard protocol such as HTTP).

Simply, you provide data (and metadata) to WIS2 by assigning it a unique identifier, in this case a URLfootnote:[The term "Uniform Resource Locator" (URL) refers to the subset of URIs that, in addition to identifying a resource, provide a means of locating the resource by describing its primary access mechanism (e.g., its network "location"). RFC3986], and making it available via a data server - most typically a Web server using the HTTP protocolfootnote:[WIS2 recommends use of HTTP secure (HTTPS) wherein the communication protocol is encrypted using Transport Layer Security (TLS)]. It's up to the data server to decide what to provide when resolving the identifier: the URL of a data granule may resolve as a representation encoded in a given data format, whereas the URL of a dataset may resolve as a description of the dataset (i.e., metadata) that includes links to access the data from which the set is comprised - either individual files (i.e., the data granules) or an interactive API that enables a user to request just the parts of the dataset they need by specifying query parameters. 

Note that WIS2 ensures highly available, rapid access to a subset of data via a collection of Global Caches (see section 2.4.3. Global Cache (TODO CROSSREF)).

More detail on data publishing is provided elsewhere in this Guide (see section 2.6.2. Publishing data, discovery metadata, and notification messages (TODO CROSSREF)).

==== How to provide data in (near) real-time

WIS2 is designed to support the data sharing needs of all WMO programmes. Among these, the World Weather Watch footnote:[WMO World Weather Watch https://wmo.int/world-weather-watch] drives specific needs for the rapid exchange of data to support weather forecasting.

To enable real-time data sharingfootnote:[In the context of WIS2, real-time implies anything from a few seconds to a few minutes - not the milliseconds required by some applications.], WIS2 uses notification messages to advertise the availability of a new resource - data or discovery metadata - and how to access that resource. Notification messages are published to a queue on a message broker and immediately delivered to everyone subscribing to that queue. A queue is associated with a specific _topic_, such as dataset.

For example, when a new temperature profile from a radio sonde deployment is added to a dataset of upper-air data measurements, a notification message would be published that includes the URL used to access the new temperature profile data. Everyone subscribing to notification messages about the upper-air measurement dataset would receive the notification message, identify the URL and download the new temperature profile data.

Note that WIS2 ensures rapid global distribution of notification messages using a network of Global Brokers (see section 2.4.2. Global Broker (TODO CROSSREF)).

Notification messages are encoded as GeoJSON (RFC 7946) and must conform to the WIS2 Notification Message (WNM) specification (TODO CROSSREF).

To ensure that data consumers can easily find the topics they want to subscribe to, data publishers must publish to a standard topic hierarchy, as specified in the WIS2 Topic Hierarchy (WTH) specification (TODO CROSSREF).

If your data needs to be shared in real-time, you must publish notification messages to a message broker using an authorized topic. It is recommended that you include the dataset identifier in the notification message (see WMO Core Metadata Profile 2 (WCMP2) specification, section 7.1.3. Identifier (TODO CROSSREF)). This allows data consumers receiving the notification to cross reference with information provided in the discovery metadata for the dataset, such as the conditions of use specified in the data policy, rights, or license.

Furthermore, the discovery metadata assocated with your dataset must include links to where one can subscribe to that topic on a message broker. The Global Discovery Catalogue will reject discovery metadata records containing links to topics outside the official topic-hierarchy. The Global Broker will only republish notification messages on topics specified in your discovery metadata records.

(TODO - using the Experimental topic)

If your data seems to relate to more than one topic, select the most appropriate one. The topic-hierarchy is not a knowledge organisation system - it is only used to ensure uniqueness of topics for publishing notification messages. Discovery metadata is used to describe a dataset; each dataset is mapped to one, and only one, topic.

More detail on publishing notification messages is provided elsewhere in this Guide (see section 2.6.2. Publishing data, discovery metadata, and notification messages (TODO CROSSREF)).

==== FAIR

(TODO)

==== Further reading for data publishers

(TODO CROSSREF for the referenced sections)

As a Data Publisher planning to operate a WIS2 Node, as a minimum you should read the following sections:
* 1.1. Introduction to WIS2
* 2.1. WIS2 Architecture
* 2.2. Roles in WIS2
* 2.4. Components of WIS2
* 2.6. Implementation and operation of WIS2 Node

The following sections are useful for further reading:
* 3.1. Information management
* 4.1. Security
* 5.1. Competencies

Note that sections _4.1. Security_ and _5.1. Competencies_ reference content originally published for WIS1. These remain largely applicable and will be updated subsequent releases of this Guide. 

If you are publishing aviation weather data via WIS2 for onward transmission through ICAO SWIM you should also read:
* 2.8.1.1. Publishing aviation weather data through WIS2 into ICAO SWIM



// include::sections/wis2node.adoc[]
