=== 1.3 Data publisher

As a data publisher with authoritative Earth system data that you want to share with the WMO community you should read the guidance presented here. In addition, a list of references to informative material in this Guide and elsewhere is provided at the end of this section.

==== How to get started

The first thing you need to do is consider your data, how it can be conceptually grouped into one or more datasets (see <<_1.1.4_why_are_datasets_so_important?>>), and whether it is core or recommended data, as per Resolution 1 (Cg-Ext 2021)).

Next, you need to consider where it is published. If your data relates to your country or territory, you need to publish it through a National Centre (NC). If your data relates to a region, programme, or other specialized function within WMO, you need to publish it through a Data Collection or Production Centre (DCPC). The functional requirements for NC and DCPC are described in the _Manual on WIS_, Volume II - Part III Functions of WIS.

All NCs and DCPCs are affiliated with a Global Information System Centre (GISC) that has a responsibility to help establish efficient and effective data sharing on the WIS. Your GISC will be able to help you in getting your data onto WIS2.

You may be able to identify an existing NC or DCPC that can publish your data. Alternatively, you may need to establish a new NC or DCPC. The main difference is that an NC is designated by a Member, whereas a DCPC is designated by a WMO or related international programme and/or a regional association.

Both NC and DCPC require the operation of a WIS2 Node (see <<_2.4.2_wis2_node>>). The procedure for registering a new WIS2 Node is provided in <<_Registration_and_decommissioning_of_a_wis2_node>>. 

Once you have determined the scope of your datasets, the data policy that applies, and have a WIS2 Node ready for data publication, you are ready to progress to the next step: providing discovery metadata.

==== 1.3.2 How to provide discovery metadata to WIS2

Discovery metadata is the mechanism by which you tell potential consumers about your data, how it may be accessed, and any conditions you may place on the use of the data.

Each dataset you want to publish must have an associated discovery metadata record. This record is encoded as GeoJSON (RFC 7946footnote:[RFC 7946 - The GeoJSON Format: https://datatracker.ietf.org/doc/html/rfc7946]) must conform to the specification given in the _Manual on WIS_, Volume II, Appendix F: WMO Core Metadata Profile.

Copies of all discovery metadata records from WIS2 are held at the Global Discovery Catalogues, where data consumers can search and browse to find data that is of interest to them. 

Depending on local arrangements, your GISC may be able to help you transfer your discovery metadata record(s) to the Global Discovery Catalogues. If this is not the case, you will need to publish the discovery metadata record(s) yourselffootnote:[In the future, WIS2 may provide metadata publication services (such as, through a WIS2 metadata management portal) to assist with this task. However, such a service is not currently available.] using one of two ways:

* The simplest method is to encode the discovery metadata record as a file and publish it to an HTTP server where it can be accessed with a URL. 
* Alternatively, you may operate a local metadata catalogue through which discovery metadata records can be shared using an API (for example, Open Geospatial Consortium (OGC) API – Recordsfootnote:[OGC API - Records - Part 1: Core https://docs.ogc.org/DRAFTS/20-004.html]). Each discovery metadata record can be accessed with a unique URL via the API (for instance, an item that is part of the discovery metadata catalogue).

In both cases, a notification message needs to be published on a Message Broker that tells WIS2 there is a new discovery metadata to upload and that it is accessed at the specified URLfootnote:[Both data and metadata publication use the same notification message mechanism to advertise the availability of a new resource.]. The notification messages shall conform to the specification given in the _Manual on WIS_, Volume II, Appendix E: WIS2 Notification Message. Furthermore, the notification message must be published on a topic that conforms to the specification given in _Manual on WIS_, Volume II, Appendix D: WIS2 Topic Hierarchy. For example, metadata published by Deutscher Wetterdienst would use the following topic: ``origin/a/wis2/de-dwd/metadata/core``

These discovery metadata records are then propagated through the Global Service components into to the Global Discovery Catalogue where data consumers can search and browse for datasets of interest.

Upon receipt of a new discovery metadata record, a Global Discovery Catalogue (see <<_2.4.4_global_discovery_catalogue>>) will validate, assess, ingest, and publish the record. Validation ensures that your discovery metadata record complies with the specification. The assessment examines your discovery metadata record against good practice. The Global Discovery Catalogue will notify you if your discovery metadata record fails validation and provide recommendations for improvements for you to consider. 

Discovery metadata must be published in the Global Discovery Catalogues before you begin publishing data.

==== 1.3.3 How to provide data to WIS2

WIS2 is based on the web architecturefootnote:[Architecture of the World Wide Web https://www.w3.org/TR/webarch/]. As such it is _resource oriented_. Datasets are resources; the "granules" of data grouped in a dataset are resources; the discovery metadata records that describe datasets are resources. In Web architecture, every resource has a unique identifier (such as a URIfootnote:[RFC 3986 - Uniform Resource Identifier (URI) - Generic Syntax: https://datatracker.ietf.org/doc/html/rfc3986]), and the unique identifier can be used to resolve the resource identified and interact with it (for example, to download a representation of the resource over an open standard protocol such as HTTP).

Simply, you provide data (and metadata) to WIS2 by assigning it a unique identifier, in this case a URLfootnote:[The term "Uniform Resource Locator" (URL) refers to the subset of URIs that, in addition to identifying a resource, provide a means of locating the resource by describing its primary access mechanism (such as its network "location"). RFC 3986], and make it available via a data server - most typically a web server using the HTTP protocolfootnote:[WIS2 strongly prefers secure versions of protocols (such as HTTPS) wherein the communication protocol is encrypted using Transport Layer Security (TLS)]. It is up to the data server to decide what to provide when resolving the identifier: the URL of a data granule may resolve as a representation encoded in a given data format, whereas the URL of a dataset may resolve as a description of the dataset (that is, metadata) that includes links to access the data from which the dataset is comprised - either individual files (that is, the data granules) or an interactive API that enables a user to request just the parts of the dataset they need by specifying query parameters.

The following sections cover specific considerations relating to publishing data to WIS2.

===== 1.3.3.1 Data formats and encodings

Whether providing data as files or through interactive APIs you need to decide which encodings (in other words, _data formats_) to use. WMO technical regulations may require that data be encoded in specific formats. For example, synoptic observations must be encoded in Binary universal form for the representation of meteorological data (BUFR). The https://library.wmo.int/idurl/4/35625[_Manual on Codes_] (WMO-No. 306) provides details of data formats formally approved for use in WMO. However, technical regulations do not cover all data sharing requirements. In such cases, you should select data formats that are open, non-proprietary, widely adopted and understood in their target user community. In this context, “open” means that anyone can use the format without needing a license to do so – either to encode data in that format or write software that understands the format.

===== 1.3.3.2 Providing data as files

The simplest way to publish data through WIS2 is to persist your data as files and publish those files on a web server. All these files need to be organized somehow – perhaps a flat structure or grouped into collections that resemble folders or directory structures.

To make your data usable, your users need to be able to find the specific file (or files) they need.

Naming conventions for files and/or directories are useful – but only when the scheme is understood. If users do not understand the naming convention, it will be a barrier to widespread reuse; many users will simply treat the filename as an opaque string. Where communities commonly use file-naming conventions (such as names with embedded metadata), these should only be used when adequate documentation is provided to users.

WIS2 does not require the use of specific naming conventions.

Another mechanism to consider is complementing the collections (such as, directories or folders in which files are grouped) with information that describes their content. Then users,both humans and software agents, can browse the structure and find what they need. Examples of this approach include:

* Web Accessible Folders (WAF) and "README" files: a web-based folder structure listing the data object files by name, where each folder contains a formatted "README" file describing the folder contents.
* SpatioTemporal Asset Catalog (STAC)footnote:[Spatio Temporal Asset Catalogue (STAC) https://stacspec.org/en]: a community standard based on GeoJSON to describe geospatial data files that can be easily indexed, browsed and accessed. Free and open source tools present STAC records (one for each data object file) through a web-based, browseable user interface.

When publishing collections of data it is tempting to package content into zip or submission information package (SIP)footnote:[See https://www.iasa-web.org/tc04/submission-information-package-sip or end of https://www.eumetsat.int/formats] resources - perhaps even packaging the entire collection, complete with folders, into a single resource. Similarly, WMO formats such as GRIB and BUFR allow multiple data objects (such as, fields or observations) to be packed into a single file. Only having to download a single resource is convenient for many users, but the downside is that the user must download the entire resource and then unpack/decompress it. The convenience of downloading fewer resources needs to be balanced against the cost of forcing users to download data they may not need. Whatever your choice, you should be guided by common practice in your domain - for example, only zip, SIP, or pack if your users expect it.

===== 1.3.3.3 Providing interactive access to data with APIs

Interactive data access aims to support efficient data workflows by enabling client applications to request only the data that they need. The advantage of interactive data access is that it provides more flexibility. Data publishers can offer an API structured around how users want to work with the data rather than forcing them to work with the structure that is convenient for you as a data publisher.

But it is more complex to implement. You need a server running software that can: 

1. Interpret a user's request; 
2. Extract the data from wherever it is stored;
3. Package that data up and send it back to the user.

Importantly, when considering the use of interactive APIs to serve your data you need to plan for costs: every request to an interactive API requires computational resources to process.

Based on the experience of data publishers who have been using web APIs to serve their communities, this Guide makes the following recommendations about interactive APIs:

* First, interactive APIs should be self-describing. A data consumer should not need to know, a priori, how to make requests from an API. They should be able to discover this information from the API endpoint itself – even if this is just a link to a documentation page they need to read.
* Second, APIs should comply with OpenAPIfootnote:[OpenAPI Specification https://spec.openapis.org/oas/v3.1.0] version 3 or later. OpenAPI provides a standardized mechanism to describe the API. Tooling (free, commercial, etc.) is widely available that can read this metadata and automatically generate client applications to query the API.
* Third, the OGC has developed a suite of APIsfootnote:[Open Geospatial Consortium OGC API https://ogcapi.ogc.org/] (called "OGC APIs") that are designed specifically to provide APIs for geospatial data workflows (discovery, vizualization, access, processing/exploitation) – all of which build on OpenAPI. Among these, OGC API – Environmental Data Retrieval (EDR)footnote:[OGC API - Environmental Data Retrieval (EDR) https://ogcapi.ogc.org/edr], OGC API – Featuresfootnote:[OGC API - Features https://ogcapi.ogc.org/features], and OGC API - Coveragesfootnote:[OGC API - Coverages https://ogcapi.ogc.org/coverages] are considered particularly useful. Because these are open standards, there is an ever-growing suite of software implementations (both free and proprietary) that support them. We recommend that data publishers assess these open-standard API specifications to determine their suitability for publishing their datasets using APIs.

Finally, you should consider versioning your API to avoid breaking changes when adding new features. A common approach is addding a _version number_ prefix into the API path; e.g., ``/v1/service/{rest-of-path}`` or ``/service/v1/{rest-of-path}``.

More guidance on the use of interactive APIs in WIS2 is anticipated in future versions of this Guide.

===== 1.3.3.4 Providing data in (near) real-time

WIS2 is designed to support the data sharing needs of all WMO disciplines and domains. Among these, the World Weather Watch footnote:[WMO World Weather Watch https://wmo.int/world-weather-watch] drives specific needs for the rapid exchange of data to support weather forecasting.

To enable real-time data sharingfootnote:[In the context of WIS2, real-time implies anything from a few seconds to a few minutes - not the milliseconds required by some applications.], WIS2 uses notification messages to advertise the availability of a new resource, either data or discovery metadata, and how to access that resource. Notification messages are published to a queue on a Message Broker in your WIS2 Nodefootnote:[WIS2 ensures rapid global distribution of notification messages using a network of Global Brokers which subscribe to message brokers of WIS2 Nodes and republish notification messages (see <<_2.4.2_Global_Broker>>).] using the MQTT protocol and immediately delivered to everyone subscribing to that queue. A queue is associated with a specific _topic_, such as dataset.

For example, when a new temperature profile from a radio sonde deployment is added to a dataset of upper-air data measurements, a notification message will be published that includes the URL used to access the new temperature profile data. Everyone subscribing to notification messages about the upper-air measurement dataset would receive the notification message, identify the URL and download the new temperature profile data.

Optionally, data may be embedded in a notification message using a ``content`` object _in addition_ to publishing via the data server. Inline data must be encoded as ``UTF-8``, ``Base64``, or ``gzip``, and must not exceed 4096 bytes in length once encoded.

Notification messages are encoded as GeoJSON (RFC 7946) and must conform to the _Manual on WIS_, Volume II, Appendix E: WIS2 Notification Message.

The URL used in the notification message should refer only to the newly added data object (for example, the new temperature profile) rather than the entire dataset. However, the WIS2 Notification Message specification allows for multiple URLs to be provided. If you are providing your data through an interactive API, you might provide a "canonical" link (designated with link relation: ``"rel": "canonical"``footnote:[IANA Link Relations https://www.iana.org/assignments/link-relations/link-relations.xhtml]), and an additional link providing the URL for the root of the web service from where one can interact with or query the entire dataset.

You should include the dataset identifier in the notification message (``metadata_id`` property). This allows data consumers receiving the notification to cross reference with information provided in the discovery metadata for the dataset, such as the conditions of use specified in the data policy, rights, or license.

Furthermore, if you have implemented controlled access to your data (e.g., the use of an API key), you should include a security object in the download link that provides the pertinent information (for example, the access control mechanism used, and where/how a data consumer would need to register to request access). 

To ensure that data consumers can easily find the topics they want to subscribe to, data publishers must publish to an authorized topic, as specified in the _Manual on WIS_, Volume II, Appendix D: WIS2 Topic Hierarchy.

If your data seems to relate to more than one topic, select the most appropriate one. The topic-hierarchy is not a knowledge organization system - it is only used to ensure the uniqueness of topics for publishing notification messages. Discovery metadata is used to describe a dataset and its relevance to additional disciplines; each dataset is mapped to one, and only one, topic.

If the WIS2 Topic Hierarchy does not include a topic appropriate for your data, your should publish on an _experimental_ topic. This allows for data exchange to be established while the formalities are consideredfootnote:[The "experimental" topic is necessary for the WIS2 pre-operational phase and future pre-operational data exchange in test mode.]. Experimental topics are provided for each Earth-system discipline at level eight in the topic hierarchy (for example, ``origin/a/wis2/{centre-id}/data/{earth-system-discipline}/experimental/``). Data publishers can can extend the experimental branch with subtopics as they deem appropriate. Experimental topics are subject to change and will be removed once they are no longer needed. For more information, see _Manual on WIS_, Volume II, Appendix D: WIS2 Topic Hierarchy, section 1.2 Publishing guidelines.

Whatever topic is used, the discovery metadata provided to the Global Discovery Catalogue must include subscription links using that topicfootnote:[The Global Discovery Catalogue will reject discovery metadata records containing links to topics outside the official topic-hierarchy.]. The Global Broker will only republish notification messages on topics specified in the discovery metadata records.

===== 1.3.3.5 Considerations when providing Core data in WIS2

Core data, as specified in Resolution 1 (Cg-Ext 2021) is considered essential for the provision of services for the protection of life and property and for the well-being of all nations. Core data is provided on a free and unrestricted basis, without charge and with no conditions on use.

WIS2 ensures highly available, rapid access to _most_ core data via a collection of Global Caches (see <<_2.4.3_global_cache>>). Global Caches subscribe to notification messages about the availability of new core data published at WIS2 Nodes, download a copy of that data and republish it on a high-performance data server and then discard it after the retention period expires (normally after 24-hoursfootnote:[A Global Cache provides short-term hosting of data. Consequently, it is not an appropriate mechanism to provide access to archives of core data, such as Essential Climate Variables. Providers of such archive data must be prepared to serve such data directly from their WIS2 Node.]). Global Caches do not provide sophisticated APIs. They publish notification messages advertising the availability of data on their caches and allow users to download data via HTTPS using the URL in the notification message.

The URL included in a notification message that is used to access core data from a WIS2 Node, or the "canonical" URL if multiple URLs are provided, must:

1. Refer to an individual data object; and
2. Be directly resolvable, such that the data object can be downloaded simply by resolving the given URL without further action.

A Global Cache will download and cache the data object accessed via this URL.  

The Global Caches are designed to support Members efficiently share real-time and near real-time data; they take on the task of making sure that core data is available to all and cover the costs of delivering data to a global community.

Unfortunately, Global Caches cannot republish _all_ core data: there is a limit to how much data they can afford to serve. Currently, a Global Cache is expected to cache about 100 GB of data each day.

If frequent updates to your dataset are very large (for example, weather prediction models or remote sensing observations) you will need to share the burden of distributing your data with the Global Cache operators. You should work with your GISC to determine the highest priority elements of your Core datasets that will be republished by the Global Caches.

For core data that is not to be cached, you must set the ``cache`` property in the notification message to ``false``footnote:[Default value for the ``cache`` property is ``true``; omission of the property will result in the data object being cached.]. 

You must ensure that core data that is not cached is publicly accessible from your WIS2 Node, that is, with no access control mechanisms in place.

A Global Cache operator may choose to disregard your cache preference - for example, if they feel that the content you are providing is large enough to impede the provision of caching services for other Membersfootnote:[Excessive data volume is not the only reason they may refuse to cache content. Other reasons include: too many small files, unreliable download from a WIS2 Node, etc.]. In such cases, the Global Cache operator will log this behaviour. In collaboration with the Global Cache operators, your GISC will work with you to resolve concerns. 

Finally, please note that Global Caches are under no obligation to cache data published on _experimental_ topics. For such data, the ``cache`` property should be set to ``false``.

===== 1.3.3.6 Implementing access control

Recommended data, as defined in Resolution 1 (Cg-Ext 2021), is exchanged on WIS2 in support of Earth system monitoring and prediction efforts and _may_ be provided with conditions on use. This means that you may control access to recommended data.

Access control should use only the "security schemes" for authentication and authorization specified in OpenAPIfootnote:[OpenAPI Security Scheme Object: https://spec.openapis.org/oas/v3.1.0#security-scheme-object].

Where access control is implemented, you should include a ``security`` object in download links provided in discovery metadata and notification messages that provide the user with pertinent information about the access control mechanism used and where/how they might register to request access. 

Recommended data is never cached by the Global Caches.

Use of core data must always be free and unrestricted. However, you may need to leverage existing systems with built-in access control when implementing the download service for your WIS2 Node. 

Example 1: API key. Your data server requires a valid API key to be included in download requests. The URLs used in notification messages should include a valid API key.footnote:[A specific API key should be used for data publication via WIS2 so that usage can be tracked.]footnote:[Given that users are encouraged to download Core data from the Global Cache, there will likely be only a few accesses using the WIS2 account's API key. If the usage quota for the WIS2 account is exceeded (for instance, further data access is blocked) then this should encourage users to download via the Global Cache as mandated in the _Manual on WIS_, Volume II.]

Example 2: Presigned URLs. Your data server uses a cloud-based object store that requires credentials to be provided when downloading data. The URLs used in notification messages should be _presigned_ with the data publisher's credentials and valid for the cache retention period (for example, 24-hours).footnote:[Working with presigned URLs on Amazon S3 https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html] 

In both cases, the URL provided in a notification message can be directly resolved without a user, or Global Cache, needing to take additional action such as providing credentials or authenticating. 

Finally, note that if you are only publishing core data, you may be able to entirely rely on the Global Caches to distribute your data. In such cases, your WIS2 Node may use Internet Protocol (IP)filtering to allow access only from Global Services. For more details, see section 2.6 Implementation and operation of a WIS2 Node.

===== 1.3.3.7 Providing access to data archives

There is no requirement for a WIS2 Node to publish notification messages about newly available data, however, the mechanism is available if needed (for instance, for real-time data exchange). Data archives published through WIS2 do not need to provide notification messages for data unless the user community has expressed a need to be rapidly notified about changes (for example, the addition of new records into a climate observation archive).

However, notification messages must still be used to share discovery metadata with WIS2. Given that the provision of metadata and subsequent updates is likely to be infrequent, it may be sufficient to "handcraft" a notification message and publish it locally on an MQTT brokerfootnote:[MQTT broker managed services are available online, often with a free (no cost) starter plan sufficient for infrequent publications of notifications about metadata. These provide a viable alternative to implementing an MQTT broker instance yourself.] or with help from a GISC. See above for more details on publishing discovery metadata to WIS2.

Note that some data archives are categorized as core data; for example, Essential Climate Variables. Core data may be distributed via the Global Caches. However, given that these provide only short-term hosting of data (for instance, 24-hours), Global Caches are not an appropriate mechanism to provide access to archives of core data. The archive must be accessed directly via the WIS2 Node.  

==== 1.3.4 Further reading for data publishers

As a data publisher planning to operate a WIS2 Node, as a minimum you should read the following sections:

* <<_1.1_introduction_to_wis2>>
* <<_2.1_wis2_architecture>>
* <<_2.2_roles_in_wis2>>
* <<_2.4_components_of_wis2>>
* <<_2.6_implementation_and_operation_of_a_wis2_node>>

The following sections are useful for further reading:

* <<_3.1_information_management>>
* <<_4.1_security>>
* <<_5.1_competencies>>

Note that sections _4.1. Security_ and _5.1. Competencies_ reference content originally published for WIS1. These remain largely applicable and will be updated in subsequent releases of this Guide. 

If you are publishing aviation weather data via WIS2 for onward transmission through the International Civil Aviation Organization (ICAO) System Wide Information Management (SWIM), you should also read: 
* <<_2.8.8.1_publishing_aviation_weather_data_through_wis2_into_icao_swim>>.

Finally, you should also review the specifications in the _Manual on WIS_, Volume II:

* Appendix D: WIS2 Topic Hierarchy
* Appendix E: WIS2 Notification Message
* Appendix F: WMO Core Metadata Profile 2

// include::sections/wis2node.adoc[]
