=== Data consumer

As a Data Consumer wanting to use data published via WIS2 you should read the guidance presented here. In addition, a list of references to informative material in this Guide and elsewhere is provided at the end of this section.

==== How to search the Global Discovery Catalogue to find Datasets

A Data Consumer may browse discovery metadata provided by the Global Discovery Catalogue to locate a Dataset of interest. Discovery metadata follows a standard scheme (see PART V Discovery Metadata TODO: fix ref). A Data Consumer may discover a Dataset using keywords, geographic area of interest, temporal information, or free text.  Matching search results from the Global Discovery Catalogue provide high-level information (title, description, keywords, spatiotemporal extents, data policy, licensing, contact information), from which a Data Consumer can assess and evaluate their interest in accessing/downloading data associated with the Dataset record.

A key component of Dataset records in the Global Discovery Catalogue is that of "actionable" links.  A Dataset record provides one to many links that clearly identify the nature and purpose of the link (informational, direct download, API, subscription) so that the Data Consumer can interact with the data accordingly.  For example, a Dataset record may include a link to subscribe to notifications (see (TODO CROSSREF) <<_how_to_subscribe_to_notifications_about_availability_of_new_data>>) about the data, or a API, or an offline archive retrieval service.

The Global Discovery Catalogue is accessible via an API and provides a low barrier mechanism (see (TODO CROSSREF) <<_global_discovery_catalogue>>).

==== How to subscribe to notifications about availability of new data

A Data Consumer can subscribe to data notifications by searching the Global Discovery Catalogue and subscribing to notifications associated with a given Dataset, or by browsing the topics provided by a Global Broker to locate a Dataset of interest to them. Topic structures follow a standard scheme (see WIS2 Topic Hierarchy TODO: crossref).  A Data Consumer can use the "canonical" link provided in a Data notification to directly download the associated data.

A Data Consumer may also discover more about the Dataset associated with a particular data notification by using the notification's metadata identifier as a key to search the Global Discovery Catalogue.

Data Consumers should subscribe to receive "data availability" messages from Global Brokers. Exceptionally, a Data Consumer may choose to subscribe directly to the local message broker at the originating NC/DCPC – but note that the NC/DCPC may not provide public access to its local message broker. Data Consumers should not subscribe to the local message broker of Global Cache instances.

Real-time and near real-time data designated as "Core" in the WMO Unified Data Policy (Resolution 1) will be available from the Global Cache. As per clause 3.2.13 from the Manual on WIS, Vol II. Data Consumers should access data from the Global Cache.

When a Dataset is available from the Global Cache, its Dataset record will include a link to subscribe to "data availability" messages from the Global Cache instances. Data Consumers will subscribe to these "Global Cache" topics and not to the topic that contains messages from the originating NC/DCPC.

==== How to use a notification message to decide whether to download data

Each Global Cache will publish a "data availability" message as the associated data object becomes available from that Global Cache instance. Each "data availability" message will refer to the same logical data object but hosted at a different location within WIS. Data Consumers need to consider their strategy for managing these duplicate messages. From a data perspective, it does not matter which Global Cache instance is used – they will all provide an identical copy of the data object published by the originating NC/DCPC. The simplest strategy is to accept the first "data availability" message and download from the Global Cache instance that the message refers to (i.e., using a URL for the data object at that Global Cache instance). Alternatively, a Data Consumer may have a preferred Global Cache instance, for example, that is located in the Region. Whichever Global Cache instance is chosen, Data Consumers will need to implement logic to discard duplicate "data availability" messages.

==== How to download data

Dataset links are made available through Dataset discovery metadata (via the Global Discovery Catalogue) as well as data notification messages (via Global Brokers). Links can be used to directly download the data (according to the network protocol and content description provided in the link) using a mechanism appropriate to the workflow of the Data Consumer. This could include web and/or desktop applications, custom tooling, or other approaches.  For data subscriptions, data notification messages provide a "canonical" link to download the associated data object.

==== How to use data

Data is shared on WIS2 in accordance with the WMO Unified Data Policy (Resolution 1 (Cg-Ext 2021)). This data policy describes two categories of data: *Core* and *Recommended*:

* Core data is considered essential for provision of services for the protection of life and 
property and for the well-being of all nations. Core data is provided on a free and unrestricted basis, without charge and with no conditions on use.
* Recommended data is exchanged on WIS2 in support of Earth system monitoring and prediction efforts. Recommended data _may_ by provided with conditions on use and/or subject to a license.

Furthermore, the WMO Unified Data Policy encourages attribution of the source of the data in all cases. In this way, credit is given to those who have expended effort and resources in collecting, curating, generating, or processing the data. Attribution provides visibility of who is using data which, for many organizations, provides necessary evidence to justify continued provision of and updates to the data.

Details of the applicable WMO data policy plus any rights or licenses associated with data are provided in the discovery metadata that accompanies the data. Discovery metadata records are available from the Global Discovery Catalogue.

The WMO Core Metadata Profile 2 specification, section 7.1.17. Properties / WMO data policy (TODO CROSSREF - WCMP2/7.1.17) provides details on how data policy, rights, and/or licenses are described in the discovery metadata.

When using data from WIS2, data consumers:

* Shall respect the conditions of use applicable to the data as expressed in the WMO data policy, rights statements, or licenses. 
* Should attribute the source of the data.
 
==== Further reading for data consumers

 (TODO CROSSREF for the referenced sections)

As a Data Publisher planning to operate a WIS2 Node, as a minimum you should read the following sections:
* 1.1. Introduction to WIS2
* 2.1. WIS2 Architecture
* 2.2. Roles in WIS2
* 2.4. Components of WIS2

The following specifications are useful for further reading:
* WMO Core Metadata Profile 2 (WCMP2) specification
* WIS2 Notification Message (WNM) specification
