=== 1.3 Data publisher

Data publishers wanting to share authoritative Earth system data that with the WMO community should read the guidance presented here. A list of references to informative material in this Guide and elsewhere is provided at the end of this section.

==== 1.3.1 How to get started

The first thing step is to consider the data, how they can be conceptually grouped into one or more datasets (see <<_1_1_4_why_are_datasets_so_important?>>), and whether they are core or recommended data, as per the Unified Data Policy (Resolution 1 (Cg-Ext(2021))) .

Next, it is important to consider where the data are published. If the data relate to a specific country or territory, they should be published through a National Centre (NC). If they relate to a region, programme, or other specialized function within WMO, they should be published through a Data Collection or Production Centre (DCPC). The functional requirements for NCs and DCPCs are described in the _Manual on WIS_, Volume II - Part III Functions of WIS.

All NCs and DCPCs are affiliated with a Global Information System Centre (GISC), which is responsible for helping to establish efficient and effective data sharing on WIS. The affiliated GISC can assist in getting the data onto WIS2.

It may be possible to identify an existing NC or DCPC that can publish the data. Alternatively, it may be necessary to establish a new NC or DCPC. The main distinction between these two centres is that an NC is designated by a Member, whereas a DCPC is designated by a WMO or related international programme and/or a regional association.

Both NCs and DCPCs require the operation of a WIS2 Node (see <<_2_4_2_wis2_node>>). The procedure for registering a new WIS2 Node is provided in <<_2_6_1_1_registration_and_decommissioning_of_a_wis2_node>>. 

Once the scope of the datasets has been determined, the applicable data policy has been identified, and a WIS2 Node is ready for data publication, the process can proceed to the next step: providing discovery metadata.

==== 1.3.2 How to provide discovery metadata to WIS2

Discovery metadata is the mechanism by which data publishers tell potential consumers about their data, how it may be accessed, and any conditions they may place on the use of those data.

Each dataset that is published must have an associated discovery metadata record. This record is encoded as GeoJSON (RFC 7946footnote:[See RFC 7946 - The GeoJSON Format: https://datatracker.ietf.org/doc/html/rfc7946.]) and must conform to the specification given in the _Manual on WIS_, Volume II - Appendix F. WMO Core Metadata Profile (Version 2).

Copies of all discovery metadata records from WIS2 are held in the Global Discovery Catalogues, where data consumers can search and browse to find data that is of interest to them. 

Depending on local arrangements, your GISC may be able to assist in transferring discovery metadata record(s) to the Global Discovery Catalogues. If this is not the case, data publishers will need to publish the discovery metadata record(s) themselvesfootnote:[In the future, WIS2 may provide metadata publication services (for example, through a WIS2 metadata management portal) to assist with this task. However, such services are not currently available.] using one of two methods:

* The simplest method is to encode the discovery metadata record as a file and publish it to an HTTP server, where it can be accessed with a URL. 
* Alternatively, a data publisher may operate a local metadata catalogue through which discovery metadata records can be shared using an API (for example, OGC API – Recordsfootnote:[See OGC API - Records - Part 1: Core https://docs.ogc.org/DRAFTS/20-004.html.]). Each discovery metadata record (for instance, an item that is part of the discovery metadata catalogue) can be accessed with a unique URL via the API .

In both cases, a notification message needs to be published on a Message Broker that tells WIS2 that there is a new discovery metadata record to upload and that it can be accessed at the specified URL.footnote:[Both data and metadata are published using the same notification message mechanism to announce the availability of new resources.] Notification messages shall conform to the specification given in the _Manual on WIS_, Volume II - Appendix E. WIS2 Notification Message. They must also be published on a topic that conforms to the specification given in the _Manual on WIS_, Volume II - Appendix D. WIS2 Topic Hierarchy. For example, metadata published by Deutscher Wetterdienst would use the following topic: ``origin/a/wis2/de-dwd/metadata/core``.

These discovery metadata records are then propagated through the Global Service components into the Global Discovery Catalogue, where data consumers can search and browse for datasets of interest.

Upon receipt of a new discovery metadata record, a Global Discovery Catalogue (see <<_2_4_4_global_discovery_catalogue>>) will validate, assess, ingest, and publish the record. Validation ensures compliance with the specification, while the assessment evaluates the discovery record against good practices. The Global Discovery Catalogue will notify the data publisher if the discovery metadata record fails validation and provide recommendations for improvements. 

Discovery metadata must be published in the Global Discovery Catalogues before the data is published.

==== 1.3.3 How to provide data to WIS2

WIS2 is based on the web architecture.footnote:[See Architecture of the World Wide Web, Volume One: https://www.w3.org/TR/webarch/.] As such it is _resource oriented_. Datasets are resources; the "granules" of data grouped in a dataset are resources; and the discovery metadata records that describe datasets are resources. In web architecture, every resource has a unique identifier (such as a URIfootnote:[See RFC 3986 - Uniform Resource Identifier (URI) - Generic Syntax: https://datatracker.ietf.org/doc/html/rfc3986]), which can be used to resolve the identifieed resource and interact with it (for example, to download a representation of the resource over an open-standard protocol such as HTTP).

In simple terms, data (and metadata) are provided to WIS2 by assigning them a unique identifier, in this case a URLfootnote:[The term "Uniform Resource Locator" (URL) refers to the subset of URIs that, in addition to identifying a resource, provide a means of locating the resource by describing its primary access mechanism (such as its network "location"). RFC 3986], and making them available via a data server - most typically a web server using HTTP protocol.footnote:[WIS2 strongly prefers secure versions of protocols (such as HTTPS) wherein the communication protocol is encrypted using Transport Layer Security (TLS)] It is up to the data server to decide what to provide when resolving the identifier. For example, the URL of a data granule may resolve as a representation encoded in a given data format, whereas the URL of a dataset may resolve as a description of the dataset (that is, metadata) that includes links to access the data from which the dataset is comprised - either individual files (that is, the data granules) or an interactive API that enables users to request only the parts of the dataset they need by specifying query parameters.

The following sections cover specific considerations relating to publishing data to WIS2.

===== 1.3.3.1 Data formats and encodings

Whether providing data as files or through interactive APIs, data publishers need to decide which encodings (_data formats_) to use. WMO technical regulations may require that data be encoded in specific formats. For example, synoptic observations must be encoded in Binary Universal Form for the Representation of meteorological data (BUFR). The https://library.wmo.int/idurl/4/35625[_Manual on Codes_] (WMO-No. 306) provides details of data formats formally approved for use in WMO. However, the technical regulations do not cover all data sharing requirements. In such cases, data publishers should select data formats that are open, non-proprietary, widely adopted, and understood in the target user community. In this context, “open” means that anyone can use the format without needing a license – either to encode data in that format or to write software that understands it.

===== 1.3.3.2 Providing data as files

The simplest way to publish data through WIS2 is to persist the data as files and publish those files on a web server. All these files need to be organized in some manner, for example, in a flat structure or grouped into collections that resemble folders or directory structures.

To ensure that the data are usable, users need to be able to find the specific file (or files) they need.

Naming conventions for files and/or directories are useful – but only if they are understood. If users do not understand the naming convention, it will be a barrier to widespread reuse, as many users will simply treat the filename as an opaque string. Where file naming conventions (such as names with embedded metadata) are commonly used by communities, they should only be used when adequate documentation is provided to users.

WIS2 does not require the use of specific naming conventions.

Another approach to enhance the usability of the data is to complement the collections (such as directories or folders in which files are grouped) with information that describes their content. Then users, both humans and software agents, can browse the structure and find what they need. Examples of this approach include:

* Web Accessible Folders (WAF) and README files: A web-based folder structure listing the data object files by name, where each folder contains a formatted README file describing the folder contents;
* SpatioTemporal Asset Catalog (STAC):footnote[See STAC: SpatioTemporal Asset Catalogs: https://stacspec.org/en.] A community standard based on GeoJSON to describe geospatial data files that can be easily indexed, browsed and accessed. Free and open source tools present STAC records (one for each data object file) through a web-based, browsable user interface.

When publishing collections of data, it is tempting to package content into zip or submission information package (SIP)footnote:[See https://www.iasa-web.org/tc04/submission-information-package-sip or https://user.eumetsat.int/resources/user-guides/formats.] resources - perhaps even to package the entire collection, including folders, into a single resource. Similarly, WMO formats such as GRIB and BUFR allow multiple data objects (such as fields or observations) to be packed into a single file. Downloading a single resource is convenient for many users, but the downside is that the user must download the entire resource and then unpack/decompress it. The convenience of downloading fewer resources must be balanced against the cost of forcing users to download data they may not need. The decision should be guided by common practice in the specific domain - for example, only using zip files, SIP resources, or packing files if this is what the users expect.

===== 1.3.3.3 Providing interactive access to data with APIs

Interactive data access aims to support efficient data workflows by enabling client applications to request only the data they need. The advantage of interactive data access is that it provides greater flexibility. Data publishers can offer an API structured around how users want to work with the data rather than forcing them to work with the structure that is convenient for the data publisher.

However, interactive data access is complex to implement. It requires a server running software that can: 

1. Interpret a user's request; 
2. Extract the data from wherever they are stored;
3. Package those data and send them back to the user.

Importantly, when considering the use of interactive APIs to serve data, it is necessary to plan for costs: every request to an interactive API requires computational resources to process.

Based on the experience of data publishers that have been using web APIs to serve their communities, this Guide makes the following recommendations regarding interactive APIs:

* First, interactive APIs should be self-describing. Data consumers should not need to know, a priori, how to make requests from an API. They should be able to discover this information from the API endpoint itself – even if this simply entails a link to a documentation page they need to read.
* Second, interactive APIs should comply with OpenAPIfootnote:[See OpenAPI Specification v3.1.0: https://spec.openapis.org/oas/v3.1.0.] version 3 or later. OpenAPI provides a standardized mechanism to describe the API. Tooling (free, commercial, etc.) that can read this metadata and automatically generate client applications to query the API is widely available.
* Third, the OGC has developed a suite of APIsfootnote:[Open Geospatial Consortium OGC API https://ogcapi.ogc.org/] (called "OGC APIs") that are specifically designed to provide APIs for geospatial data workflows (discovery, visualization, access, processing/exploitation) – all of which build on OpenAPI. Among these, OGC API – Environmental Data Retrieval (EDR),footnote:[OGC API - Environmental Data Retrieval (EDR) https://ogcapi.ogc.org/edr] OGC API – Features,footnote:[OGC API - Features https://ogcapi.ogc.org/features] and OGC API - Coveragesfootnote:[OGC API - Coverages https://ogcapi.ogc.org/coverages] are considered particularly useful. Because these are open standards, there is an ever-growing suite of software implementations (both free and proprietary) that support them. It is recommended that data publishers assess these open-standard API specifications to determine their suitability for publishing their datasets using APIs.

Finally, it is advisable to consider versioning the API to avoid breaking changes when adding new features. A common approach is to add a _version number_ prefix into the API path, for example, ``/v1/service/{rest-of-path}`` or ``/service/v1/{rest-of-path}``.

More guidance on the use of interactive APIs in WIS2 is anticipated in future versions of this Guide.

===== 1.3.3.4 Providing data in (near) real time

WIS2 is designed to support the data sharing needs of all WMO disciplines and domains. Among these, the World Weather Watch footnote:[WMO World Weather Watch https://wmo.int/world-weather-watch] drives specific needs for the rapid exchange of data to support weather forecasting.

To enable real-time data sharing,footnote:[In the context of WIS2, real time implies anything from a few seconds to a few minutes - not the milliseconds required by some applications.] WIS2 uses notification messages to inform users of the availability of a new resource, either data or discovery metadata, and how they can access that resource. Notification messages are published to a queue on a Message Broker in a data publisher's WIS2 Nodefootnote:[WIS2 ensures the rapid global distribution of notification messages using a network of Global Brokers which subscribe to the Message Brokers of WIS2 Nodes and republish notification messages (see <<_2_4_2_Global_Broker>>).] using the MQTT protocol and immediately delivered to all users subscribing to that queue. A queue is associated with a specific _topic_, such as a dataset.

For example, when a new temperature profile from a radiosonde deployment is added to a dataset of upper-air data measurements, a notification message will be published that includes the URL used to access the new temperature profile data. All subscribers to notification messages about the upper-air measurement dataset will receive the notification message and be able to identify the URL and download the new temperature profile data.

Optionally, data may be embedded in a notification message using a content object in addition to being published via the data server. Inline data must be encoded as ``UTF-8``, ``Base64``, or ``gzip``, and must not exceed 4096 bytes in length once encoded.

Notification messages are encoded as GeoJSON (RFC 7946) and must conform to the _Manual on WIS_, Volume II, Appendix E. WIS2 Notification Message.

The URL used in the notification message should refer only to the newly added data object (for example, the new temperature profile), rather than the entire dataset. However, the WIS2 Notification Message specification allows for multiple URLs to be provided. When providing data through an interactive API, it may be useful to provide a "canonical" link (designated by link relation: ``"rel": "canonical"``footnote:[IANA Link Relations https://www.iana.org/assignments/link-relations/link-relations.xhtml]) and an additional link with the URL for the root of the web service from which the entire dataset can be accessed or queried.

The dataset identifier should be included in the notification message (``metadata_id`` property). This allows data consumers receiving the notification to cross reference it with information provided in the discovery metadata for the dataset, for example the conditions of use specified in the data policy, rights, or license.

If controlled access to the data has been implemented (for example, the use of an API key), the download link should include a security object which provides the pertinent information (the access control mechanism used, where or how a data consumer needs to register to request access, and so forth). 

To ensure that data consumers can easily find the topics they want to subscribe to, data publishers must publish to an authorized topic, as specified in the _Manual on WIS_, Volume II, Appendix D. WIS2 Topic Hierarchy.

If the data seem to relate to more than one topic, the most appropriate one should be selected. The topic hierarchy is not a knowledge organization system – it is used solely to ensure the uniqueness of topics for publishing notification messages. Discovery metadata is used to describe a dataset and its relevance to additional disciplines; each dataset is mapped to one, and only one, topic.

If the WIS2 Topic Hierarchy does not include a topic appropriate for the data, the data should be published on an experimental topic. This will allow data exchange to be established while the formalities are being considered.footnote:[The "experimental" topic is necessary for the WIS2 pre-operational phase and future pre-operational data exchange in test mode.] Experimental topics are provided for each Earth system discipline at level eight in the topic hierarchy (for example, ``origin/a/wis2/{centre-id}/data/{earth-system-discipline}/experimental/``). Data publishers can extend the experimental branch with subtopics they deem appropriate. Experimental topics are subject to change and will be removed once they are no longer needed. For more information, see _Manual on WIS_, Volume II, Appendix D. WIS2 Topic Hierarchy, section 1.2 Publishing guidelines.

Whatever topic is used, the discovery metadata provided to the Global Discovery Catalogue must include subscription links using that topic.footnote:[The Global Discovery Catalogue will reject discovery metadata records containing links to topics outside the official topic-hierarchy.] The Global Broker will only republish notification messages on topics specified in the discovery metadata records.

===== 1.3.3.5 Considerations when providing core data in WIS2

Core data, as specified in the Unified Data Policy (Resolution 1 (Cg-Ext(2021))) are considered essential for the provision of services for the protection of life and property and for the well-being of all nations. Core data is provided on a free and unrestricted basis, without charge and with no conditions on use.

WIS2 ensures highly available, rapid access to _most_ core data via a collection of Global Caches (see <<_2_4_3_global_cache>>). Global Caches subscribe to notification messages about the availability of new core data published from WIS2 Nodes, download a copy of that data and republish it on a high-performance data server and then discard it after the retention period expires (normally after 24 hours.footnote:[A Global Cache provides short-term hosting of data. Consequently, it is not an appropriate mechanism to provide access to archives of core data, such as Essential Climate Variables. Providers of such archive data must be prepared to serve such data directly from their WIS2 Node.]) Global Caches do not provide sophisticated APIs. They publish notification messages advertising the availability of data on their caches and allow users to download data via HTTPS using the URL in the notification message.

The URL included in a notification message that is used to access core data from a WIS2 Node, or the "canonical" URL, if multiple URLs are provided, must:

1. Refer to an individual data object; and
2. Be directly resolvable, such that the data object can be downloaded simply by resolving the given URL without further action.

A Global Cache will download and cache the data object accessed via this URL.  

The Global Caches are designed to help Members efficiently share real-time and near-real-time data. They ensure that core data are available to all on a free and unrestricted basis, as required by the WMO Unified Data Policy (Resolution 1 (Cg-Ext(2021))).

Unfortunately, Global Caches cannot republish _all_ core data; there is a limit to how much data they can afford to serve. Currently, a Global Cache is expected to cache about 100 GB of core data each day.

If frequent updates to a dataset are very large (for example, in the case of weather prediction models or remote sensing observations) data publishers will need to share the burden of distributing their data with Global Cache operators. They should work with their GISC to determine the highest priority elements of their datasets that will be republished by the Global Caches.

Core data that are not to be cached must have the cache property in the notification message set to false.footnote:[Default value for the ``cache`` property is ``true``; omission of the property will result in the data object being cached.] 

Data publishers must ensure that core data that are not cached are publicly accessible from their WIS2 Node, that is, with no access control mechanisms in place.

Global Cache operators may choose to disregard a cache preference, for example, if they feel that the content being providing is large enough to impede the provision of caching services for other Members.footnote:[Excessive data volume is not the only reason they may refuse to cache content. Other reasons include: too many small files, unreliable download from a WIS2 Node, etc.] In such cases, the Global Cache operator will log this behaviour. Global Cache operators will collaborate with data publishers and their GISCs to resolve any concerns. 

Finally, note that Global Caches are under no obligation to cache data published on _experimental_ topics. For such data, the ``cache`` property should be set to ``false``.

===== 1.3.3.6 Implementing access control

Recommended data, as defined in the WMO Unified Data Policy (Resolution 1 (Cg-Ext(2021))), are exchanged on WIS2 in support of Earth system monitoring and prediction efforts and may be provided with conditions on use. This means that the data publisher may control access to recommended data.

Access control should only use the "security schemes" for authentication and authorization specified in OpenAPI.footnote:[OpenAPI Security Scheme Object: https://spec.openapis.org/oas/v3.1.0#security-scheme-object]

Where access control is implemented, a ``security`` object should be included in the download links in discovery metadata and notification messages to provide the user with pertinent information about the access control mechanism used and where/how they might register to request access.

Recommended data are never cached by the Global Caches.

The use of core data must always be free and unrestricted. However, it may be necessary to leverage existing systems with built-in access control when implementing the download service for the WIS2 Node. 

Example 1: API key. The data server requires a valid API key to be included in download requests. The URLs used in notification messages should include a valid API key.footnote:[A specific API key should be used for data publication via WIS2 so that usage can be tracked.], footnote:[Given that users are encouraged to download Core data from the Global Cache, there will likely be only a few accesses using the WIS2 account's API key. If the usage quota for the WIS2 account is exceeded (for instance, further data access is blocked) then this should encourage users to download via the Global Cache as mandated in the _Manual on WIS_, Volume II.]

Example 2: Presigned URLs. The data server uses a cloud-based object store that requires credentials to be provided when downloading data. The URLs used in notification messages should be _presigned_ with the data publisher's credentials and valid for the cache retention period (for example, 24 hours).footnote:[Working with presigned URLs on Amazon S3 https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html] 

In both cases, the URL provided in a notification message can be directly resolved without requiring a user or a Global Cache to take additional action, such as providing credentials or authenticating. 

Finally, note that if only core data are being published, it may be possible to rely entirely on the Global Caches to distribute the data. In such cases, the WIS2 Node may use Internet Protocol (IP) filtering to allow access only from Global Services. For more details, see 2.6 Implementation and operation of a WIS2 Node.

===== 1.3.3.7 Providing access to data archives

There is no requirement for a WIS2 Node to publish notification messages about newly available data; however, the mechanism is available if needed (for instance, for real-time data exchange). Data archives published via WIS2 do not need to provide notification messages for data unless the user community has expressed a need to be rapidly notified about changes (for example, the addition of new records to a climate observation archive).

However, notification messages must still be used to share discovery metadata with WIS2. Given that the provision of metadata and subsequent updates are likely to be infrequent, it may be sufficient to "handcraft" notification messages as needed and publish them locally on an MQTT brokerfootnote:[MQTT broker managed services are available online, often with a free (no cost) starter plan sufficient for infrequent publications of notifications about metadata. These provide a viable alternative to implementing an MQTT broker instance yourself.] or with the help of a GISC. See above for more details on publishing discovery metadata to WIS2.

Note that some data archives, for example, Essential Climate Variables, are categorized as core data. Core data may be distributed via the Global Caches; however, given that they provide only short-term data hosting (for instance, for 24 hours), Global Caches are not an appropriate mechanism to provide access to core data archives. These archives must be accessed directly via the WIS2 Node.  

==== 1.3.4 Further reading for data publishers

Data publishers planning to operate WIS2 Nodes, at a minimum, should read the following sections:

* <<_1_1_introduction_to_wis2>>
* <<_2_1_wis2_architecture>>
* <<_2_2_roles_in_wis2>>
* <<_2_4_components_of_wis2>>
* <<_2_6_implementation_and_operation_of_a_wis2_node>>

The following sections are recommended for further reading:

* <<_3_1_information_management>>
* <<_4_1_security>>
* <<_5_1_competencies>>

Note that _4.1. Security_ and _5.1. Competencies_ reference content originally published for WIS1. These sections remain largely applicable and will be updated in subsequent releases of this Guide. 

Data publishers publishing aviation weather data via WIS2 for onward transmission through the International Civil Aviation Organization (ICAO) System Wide Information Management (SWIM), should also read <<_2_8_8_1_publishing_aviation_weather_data_through_wis2_into_icao_swim>>.

Finally, data publishers should also review the specifications in the _Manual on WIS_, Volume II:

* Appendix D. WIS2 Topic Hierarchy
* Appendix E. WIS2 Notification Message
* Appendix F. WMO Core Metadata Profile (Version 2)

// include::sections/wis2node.adoc[]
