=== Data publisher

As a Data Publisher planning to operate a WIS node, you should read the following sections: TODO: fix crossrefs
* 1.2: What is WIS2?
* 1.3 Why are Datasets so important?
* PART III Data Metadata flows
* PART X Information Management

==== How to publish Dataset discovery metadata to the Global Discovery Catalogue

A Data Producer publishes discovery metadata to the Global Discovery Catalogue by creating a discovery metadata record (see TODO: ref Discovery Metadata), making it available for download, and publishing a notification of its availability (see TODO: ref How to publish data notifications).  Global Discovery Catalogues subscribed to the relevant topic via a Global Broker, receive the notification message and then validate, ingest, and publish the associated Dataset discovery metadata record.

==== How to publish data notifications

A Data Producer publishes data notifications by generating a notification message (see  TODO: ref Notification messages) via a WIS2 Node in accordance with the standard topic hierarchy. Global Brokers subscribe to WIS2 Nodes and then re-publish the data notification to any consumer with a corresponding subscription.

==== How to publish data to the Global Broker

Data publishing is realized as a function of publishing data notifications (see 2.1.2 How to publish data notifications ).

TODO: To be completed

// include::sections/wis2node.adoc[]
