=== 1.1 Introduction to WIS2

Since the Global Telecommunication System (GTS) entered operational life in 1971, it has been a reliable real-time exchange mechanism of essential data for WMO Members.

In 2007, the WMO Information System (WIS) entered operations to complement the GTS, providing a searchable catalogue and a Global Cache to enable additional discovery, access and retrieval. The success of WIS was limited as the system only partially met the requirement of providing simple access to WMO data. Today’s technology developed for the Internet of Things (IoT) opens the possibility of creating a WIS2 that is able to stand to its expectations of delivering an increasing number and volume of real-time data to WMO centres in a reliable and cost -effective way.

WIS2 has been designed to meet the shortfalls of the current WIS and GTS, support Resolution 1 (Cg-Ext(2021)) – WMO Unified Policy for the International Exchange of Earth System Data (https://library.wmo.int/idviewer/57850/[_World Meteorological Congress: Abridged Final Report of the Extraordinary Session_] (WMO-No. 1281)), support the Global Basic Observing Network (GBON) and meet the demand for high data volume, variety, velocity and veracity.

WIS2 technical framework is based around three foundational pillars: leveraging open standards, simpler data exchange and cloud-ready solutions.

==== 1.1.1 Leveraging open standards

WIS2 leverages open standards to take advantage of the ecosystem of technologies available on the market and avoid building bespoke solutions that can force National Meteorological and Hydrological Services (NMHS) to procure costly systems and equipment. In today’s standards development ecosystem, standards bodies work closely together to minimize overlap and build on one another’s areas of expertise. For example, the World Wide Web Consortium provides the framework of web standards, which the Open Geospatial Consortium and other standards bodies leverage. WIS2 leverages open standards with industry adoption and wider, stable and robust implementations, thus extending the reach of WMO data sharing and lowering the barrier to access by Members.

==== 1.1.2 Simpler data exchange

WIS2 prioritizes public telecommunication networks, unlike private networks for GTS links. As a result, using the Internet will enable the best choice for a local connection, using commonly available and well-understood technology.

WIS2 aims to improve the discovery, access and utilization of weather, climate and water data by adopting web technologies proven to provide a truly collaborative platform for a more participatory approach. Data exchange using the Web also facilitates easy access mechanisms. Browsers and search engines allow web users to discover data without specialized software. The Web also enables additional data access platforms, such as desktop Geographical Information Systems (GIS), mobile applications and forecaster workstations. The Web provides access control and security mechanisms that can be utilized to freely share core data as defined by Resolution 1 (Cg-Ext(2021)) and protect the data with more restrictive licensing constraints. Web technologies also allow for authentication and authorization for the provider to retain control of who can access published resources and to request users to accept a license specifying the terms and conditions for using the data as a condition for providing access to them.

WIS2 uses a "publish-subscribe" pattern where users subscribe to a topic to receive new data in real -time. The mechanism is like WhatsApp and other messaging applications. It is a reliable and straightforward way to allow the user to choose her data of interest and to receive them reliably.

==== 1.1.3 Cloud-ready solutions

The cloud provides reliable platforms for data sharing and processing. It reduces the need for expensive local IT infrastructure, which constitutes a barrier to developing effective and reliable data processing workflows for some WMO Members. WIS2 encourages WMO centres to adopt cloud technologies where appropriate to meet their users' needs. While WMO technical regulations will not mandate cloud services, WIS2 will promote a gradual adoption of cloud technologies that provide the most effective solution.

The cloud-based infrastructure allows easy portability of technical solutions, ensuring that a system implemented by a specific country can be packaged and deployed easily in other countries with similar needs. In addition, using cloud technologies allows WIS2 to deploy infrastructure and systems efficiently with minimum effort for the NMHSs by shipping ready-made services and implementing consistent data processing and exchange techniques.

It should be clear that hosting data and services on the cloud does not affect data ownership. Even in a cloud environment, organizations retain ownership of their data, software, configuration and change management as if they were hosting their infrastructure. As a result, data authority and provenance stay with the organization, and the cloud is simply a technical means to publish the data.

==== 1.1.4 Why are datasets so important?

WMO enables the international exchange of observations and model data for all Earth-system disciplines.

Resolution 1 (Cg-Ext(2021)) describes the Earth system data that are necessary for efforts to monitor, understand and predict the weather and climate – including the hydrological cycle, the atmospheric environment and space weather.

WIS is the mechanism by which this Earth system data is exchanged.

A common practice when working with data is to group them into "datasets". All the data in a dataset share some common characteristics. The Data Catalog Vocabulary (DCAT) defines a dataset as a "collection of data, published or curated by a single agent, and available for access or download in one or more representations" footnote:[Data Catalog Vocabulary (DCAT) - Version 2, W3C Recommendation 04 February 2020 https://www.w3.org/TR/vocab-dcat-2/#Class:Dataset].

Why is this important? The "single agent" (such as a single organization) responsible for managing the collection ensures consistency among the data. For example, in a dataset:

* All the data should be of the same type (for example, observations from weather stations).
* All the data should have the same license and/or usage conditions.
* All the data should be subject to the same quality management regime - which may mean that all the data is collected or created using the same processes.
* All the data should be encoded in the same way (such as, using the same data formats and vocabularies).
* All the data should be accessible using the same protocols - ideally from a single location.

This consistency means that one can predict what data is in a dataset, at least as far as the common characteristics, making it easier to write applications to process the data.

A dataset might be published as an immutable resource (such as, data collected from a research programme), or it might be routinely updated (for example, every minute as new observations are collected from weather stations).

A dataset may be represented as a single, structured file or object (for example, a CSV file where each row represents a data record) or as thousands of consistent files (for example, output from a reanalysis model encoded as many thousands as possible of General Regularly-distributed Information in Binary form (GRIB) files). Determining the best way to represent a dataset is beyond the scope of this Guide – there are many factors to consider. The key point here is that we consider the dataset to be a single, identifiable resource irrespective of how it is represented.

Because we group data into a single, conceptual resource (that is, the dataset) we can:
* Give this resource an identifier and use this identifier to unambiguously refer to collections of data;
* Make statements about the dataset (that is, metadata) and infer that these statements apply to the entire collection.

The dataset concept is central to WIS:
* We publish discovery metadata about datasets, as specified in the _Manual on WIS_, Volume II – Appendix F: WMO Core Metadata Profile;
* We can search for datasets that contain relevant data using the Global Discovery Catalogue (see <<_2.4.4_global_discovery_catalogue>>);
* We can subscribe to notifications about updates about a dataset via a Global Broker (see <<_2.4.2_global_broker>>);
* We can access the data that comprises a dataset from a single location using a well -described mechanism.

It is up to the data publisher to decide how their data is grouped into datasets – effectively, to decide what datasets they publish to WIS. That said, we recommend that, subject to the consistency rules above, data publishers should organize their data into as few datasets as possible.

For a data publisher, this means fewer discover metadata records to maintain. For a data consumer this means fewer topics to subscribe to and fewer places to access the data.

There are some things that are fixed requirements for datasets:

1. All data in the dataset must be accessible from a single location.
2. All data in the dataset must be subject to the same license or usage conditions.

Here are some examples of datasets:

* The most recent 5-days of synoptic observations for an entire country or territory footnote:[Why 5-days in this example? Because the system used to publish the data in this example only retains data for 5-days].
* Longterm record of observed water quality for a managed set of hydrological stations.
* Output from the most recent 24-hours of operational numerical weather prediction model runs.
* Output from 6-months of experimental model runs. It is important to note that output from the operational and experimental should not be merged into the same dataset because they use different algorithms - it is very useful to be able to distinguish the provenance (or lineage) of data.
* A multipetabyte global reanalysis spanning 1950 to present day.

In summary, datasets are important because they are how data is managed in WIS.
