FILE_BASENAME=wis2-guide-DRAFT

html:
	asciidoctor -a allow-uri-read --trace -o ${FILE_BASENAME}.html index.adoc

pdf:
	asciidoctor -a allow-uri-read --trace -r asciidoctor-pdf --trace -b pdf -o ${FILE_BASENAME}.pdf index.adoc

docx:
	asciidoctor -a allow-uri-read --trace --backend docbook --out-file - index.adoc | pandoc --from docbook --to docx --output ${FILE_BASENAME}.docx

linkcheck:
	find . -name "???.adoc" -exec asciidoc-link-check -p -c ./asciidoc-link-check-config.json {} \;

.PHONY: html pdf docx linkcheck
